# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    uds/skip-sm-mutate: "true"
  name: envoy-gateway-metrics
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      control-plane: envoy-gateway
{{- end }}
