# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfPackageConfig
metadata:
  name: velero
components:
  - name: velero
    import:
      local:
        - path: ./flavors/velero-upstream.yaml
        - path: ./flavors/velero-registry1.yaml
        - path: ./flavors/velero-unicorn.yaml
