# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

global:
  images:
    envoyGateway:
      image: registry1.dso.mil/ironbank/opensource/envoy_proxy/community/gateway@sha256:516f14930591fdb8b9c09ead66a692bb4364c90d98d699a4b6d82ded21bacfaa
