# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

global:
  images:
    envoyGateway:
      image: cgr.dev/defenseunicorns.com/envoy-gateway-fips:v1.8.3
    envoyProxy:
      image: cgr.dev/defenseunicorns.com/envoy-fips:distroless-v1.38.3
