# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

global:
  images:
    envoyGateway:
      image: docker.io/envoyproxy/gateway:v1.8.3
    envoyProxy:
      image: docker.io/envoyproxy/envoy:distroless-v1.39.0
