# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- $misdirectedRequest := .Values.misdirectedRequest }}
{{- if $misdirectedRequest.enabled }}
{{- $gateways := $misdirectedRequest.gateways | default (list "") }}
{{- range $gateway := $gateways }}
{{- if $gateway }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-{{ $gateway }}-gateway
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: misdirected-request
  namespace: {{ if $gateway }}istio-{{ $gateway }}-gateway{{ else }}istio-system{{ end }}
spec:
  {{- if $gateway }}
  workloadSelector:
    labels:
      app: {{ $gateway }}-ingressgateway
  {{- end }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                local server_name = request_handle:streamInfo():requestedServerName()
                local authority = request_handle:headers():get(":authority") or ""
                if server_name ~= "" and not string.find(authority, server_name, 1, true) then
                  request_handle:respond({[":status"] = "421"}, "Misdirected Request")
                end
              end
{{- end }}
{{- end }}
