# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: virt-api-peerauth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      kubevirt.io: virt-api
  mtls:
    mode: STRICT
  portLevelMtls:
    8443:
      mode: PERMISSIVE
