# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: uds-loki-uptime
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: uds-logging-loki-uptime
      rules:
        - record: uds:loki-backend:up
          labels:
            uds_layer: logging
            uds_component: loki-backend
          expr: |
            (
              clamp_max(kube_statefulset_status_replicas_available{statefulset="loki-backend", namespace="loki"}, 1)
              or on()
              (absent(kube_statefulset_status_replicas_available{statefulset="loki-backend", namespace="loki"}) * 0)
            )
            * on() group_left()
            kube_state_metrics:up

        - record: uds:loki-write:up
          labels:
            uds_layer: logging
            uds_component: loki-write
          expr: |
            (
              clamp_max(kube_statefulset_status_replicas_available{statefulset="loki-write", namespace="loki"}, 1)
              or on()
              (absent(kube_statefulset_status_replicas_available{statefulset="loki-write", namespace="loki"}) * 0)
            )
            * on() group_left()
            kube_state_metrics:up

        - record: uds:loki-gateway:up
          labels:
            uds_layer: logging
            uds_component: loki-gateway
          expr: |
            (
              clamp_max(kube_deployment_status_replicas_available{deployment="loki-gateway", namespace="loki"}, 1)
              or on()
              (absent(kube_deployment_status_replicas_available{deployment="loki-gateway", namespace="loki"}) * 0)
            )
            * on() group_left()
            kube_state_metrics:up

        - record: uds:loki-read:up
          labels:
            uds_layer: logging
            uds_component: loki-read
          expr: |
            (
              clamp_max(kube_deployment_status_replicas_available{deployment="loki-read", namespace="loki"}, 1)
              or on()
              (absent(kube_deployment_status_replicas_available{deployment="loki-read", namespace="loki"}) * 0)
            )
            * on() group_left()
            kube_state_metrics:up
{{- end }}
