# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# action.yml
name: "Setup Environment"
description: "UDS Environment Setup"
inputs:
  ghToken:
    description: "GITHUB_TOKEN"
    required: false
    default: ''
  registry1Username:
    description: "IRON_BANK_ROBOT_USERNAME"
    required: false
    default: ''
  registry1Password:
    description: "IRON_BANK_ROBOT_PASSWORD"
    required: false
    default: ''
  rapidfortUsername:
    description: "RAPIDFORT_USERNAME"
    required: false
    default: ''
  rapidfortPassword:
    description: "RAPIDFORT_PASSWORD"
    required: false
    default: ''
  installUv:
    description: "Whether to install uv"
    required: false
    default: 'false'
  installK3d:
    description: "Whether to install k3d"
    required: false
    default: 'false'
  installHelmUnittest:
    description: "Whether to install the helm unittest plugin"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Tools
      uses: ./.github/actions/setup-tools
      with:
        installUv: ${{ inputs.installUv }}
        installK3d: ${{ inputs.installK3d }}
        installHelmUnittest: ${{ inputs.installHelmUnittest }}

    - name: Iron Bank Login
      if: ${{ inputs.registry1Username != '' && inputs.registry1Password != '' }}
      env:
        REGISTRY_USERNAME: ${{ inputs.registry1Username }}
        REGISTRY_PASSWORD: ${{ inputs.registry1Password }}
      run: echo "${{ env.REGISTRY_PASSWORD }}" | uds zarf tools registry login -u "${{ env.REGISTRY_USERNAME }}" --password-stdin registry1.dso.mil
      shell: bash

    - name: GHCR Login
      if: ${{ inputs.ghToken != '' }}
      env:
        GH_TOKEN: ${{ inputs.ghToken }}
      run: echo "${{ env.GH_TOKEN }}" | uds zarf tools registry login -u "dummy" --password-stdin ghcr.io
      shell: bash

    - name: Maru Login
      if: ${{ inputs.ghToken != '' }}
      run: |
        echo "MARU_AUTH=\"{\"raw.githubusercontent.com\": \"${{ inputs.ghToken }}\"}\"" >> "$GITHUB_ENV"
      shell: bash

    - name: Rapidfort Login
      if: ${{ inputs.rapidfortUsername != '' && inputs.rapidfortPassword != '' }}
      shell: bash
      env:
        RAPIDFORT_USERNAME: ${{ inputs.rapidfortUsername }}
        RAPIDFORT_PASSWORD: ${{ inputs.rapidfortPassword }}
      run: echo "${{ env.RAPIDFORT_PASSWORD }}" | uds zarf tools registry login -u "${{ env.RAPIDFORT_USERNAME }}" --password-stdin quay.io
