# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

license: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
copyright: Defense Unicorns
ignore:
  - .husky/
  - .husky/**
