# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

package:
  gateway: tenant
  host: portal
  domain: "###ZARF_VAR_DOMAIN###"

sso:
  enabled: true
