# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Annotations for the managed Gateway's LoadBalancer Service (e.g. AWS needs these for UDP)
envoyService:
  annotations: {}
