{
 "title": "UDS / Monitoring / Probe Uptime",
 "tags": [
  "uds",
  "blackbox-exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Probe Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "% Uptime (this period)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success[$__range]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Cert Expiry",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry - time()) / 86400",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}