{
 "title": "UDS / Monitoring / Core Uptime",
 "tags": [
  "uds",
  "uptime"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "UDS Core Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uds:core:up", "legendFormat": "Core Uptime" }
   ]
  },
  {
   "title": "Component Status",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{__name__=~\"uds:.+:up\"}",
     "legendFormat": "{{uds_component}}"
    }
   ]
  },
  {
   "title": "% Uptime (this period)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"uds:.+:up\"}[$__range]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}