# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

loki:
  image:
    registry: cgr.dev/defenseunicorns.com
    repository: loki-fips
    tag: v3.7.2
gateway:
  image:
    registry: cgr.dev/defenseunicorns.com
    repository: nginx-fips
    tag: v1.31.0
memcached:
  image:
    registry: cgr.dev/defenseunicorns.com
    repository: memcached-fips
    tag: v1.6.42
sidecar:
  image:
    registry: cgr.dev
    repository: defenseunicorns.com/k8s-sidecar-fips
    tag: v2.7.3
