# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: istio-egress-ambient
component:
  charts:
    - name: uds-istio-egress-config
      namespace: istio-egress-ambient
      local:
        path: charts/uds-istio-egress-config
