# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: istio-egress-gateway
component:
  charts:
    - name: gateway
      releaseName: egressgateway
      namespace: istio-egress-gateway
      helmRepository:
        url: https://istio-release.storage.googleapis.com/charts
        name: gateway
        version: 1.29.2
      valuesFiles:
        - values/base-egress.yaml
