# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: istio-controlplane
  description: "UDS Core Istio package deploys Istio with admin, tenant and passthrough gateways."
variables:
  - name: DOMAIN
    description: "Cluster domain"
    default: "uds.dev"
  - name: ADMIN_DOMAIN
    description: "Domain for admin services, defaults to `admin.DOMAIN`"
variants:
  - target:
      flavor: upstream
    import:
      path: common-istio-controlplane.yaml
    charts:
      - name: istiod
        valuesFiles:
          - values/upstream/istiod.yaml
      - name: cni
        valuesFiles:
          - values/upstream/cni.yaml
      - name: ztunnel
        valuesFiles:
          - values/upstream/ztunnel.yaml
    images:
      - name: docker.io/istio/pilot:1.29.2-distroless
      - name: docker.io/istio/proxyv2:1.29.2-distroless
      - name: docker.io/istio/install-cni:1.29.2-distroless
      - name: docker.io/istio/ztunnel:1.29.2-distroless

  - target:
      flavor: registry1
    import:
      path: common-istio-controlplane.yaml
    charts:
      - name: istiod
        valuesFiles:
          - values/registry1/istiod.yaml
      - name: cni
        valuesFiles:
          - values/registry1/cni.yaml
      - name: ztunnel
        valuesFiles:
          - values/registry1/ztunnel.yaml
    images:
      - name: registry1.dso.mil/ironbank/tetrate/istio/proxyv2:1.29.2-fips
      - name: registry1.dso.mil/ironbank/tetrate/istio/pilot:1.29.2-fips
      - name: registry1.dso.mil/ironbank/tetrate/istio/install-cni:1.29.2-fips
      - name: registry1.dso.mil/ironbank/tetrate/istio/ztunnel:1.29.2-fips

  - target:
      flavor: unicorn
    import:
      path: common-istio-controlplane.yaml
    charts:
      - name: istiod
        valuesFiles:
          - values/unicorn/istiod.yaml
      - name: cni
        valuesFiles:
          - values/unicorn/cni.yaml
      - name: ztunnel
        valuesFiles:
          - values/unicorn/ztunnel.yaml
    images:
      - name: quay.io/rfcurated/istio/pilot:1.29.2-jammy-fips-rfcurated-rfhardened
      - name: quay.io/rfcurated/istio/proxyv2:1.29.2-jammy-fips-rfcurated-rfhardened
      - name: quay.io/rfcurated/istio/install-cni:1.29.2-jammy-fips-rfcurated-rfhardened
      - name: quay.io/rfcurated/istio/ztunnel:1.29.2-jammy-scratch-fips-rfcurated
