# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: istio-controlplane
component:
  target:
    flavor: unicorn
  import:
    paths:
      - common/istio-controlplane.yaml
  charts:
    - name: istiod
      valuesFiles:
        - values/unicorn/istiod.yaml
    - name: cni
      valuesFiles:
        - values/unicorn/cni.yaml
    - name: ztunnel
      valuesFiles:
        - values/unicorn/ztunnel.yaml
  images:
    - name: quay.io/rfcurated/istio/pilot:1.29.2-jammy-fips-rfcurated-rfhardened
    - name: quay.io/rfcurated/istio/proxyv2:1.29.2-jammy-fips-rfcurated-rfhardened
    - name: quay.io/rfcurated/istio/install-cni:1.29.2-jammy-fips-rfcurated-rfhardened
    - name: quay.io/rfcurated/istio/ztunnel:1.29.2-jammy-scratch-fips-rfcurated
