# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfPackageConfig
metadata:
  name: istio
components:
  - name: istio-controlplane
    import:
      paths:
        - flavors/istio-controlplane-upstream.yaml
        - flavors/istio-controlplane-registry1.yaml
        - flavors/istio-controlplane-unicorn.yaml

  - name: gateway-api-crds
    import:
      paths:
        - common/gateway-api-crds.yaml

  - name: istio-admin-gateway
    import:
      paths:
        - istio-admin-gateway.yaml

  - name: istio-tenant-gateway
    import:
      paths:
        - istio-tenant-gateway.yaml

  - name: istio-passthrough-gateway
    import:
      paths:
        - istio-passthrough-gateway.yaml

  - name: istio-egress-ambient
    import:
      paths:
        - istio-egress-ambient.yaml

  - name: istio-egress-gateway
    import:
      paths:
        - istio-egress-gateway.yaml
