# Copyright 2025-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: cgr.dev
  repository: defenseunicorns.com/falco-fips
  tag: v0.44.1
  pullPolicy: IfNotPresent

falcosidekick:
  image:
    registry: cgr.dev
    repository: defenseunicorns.com/falcosidekick-fips
    tag: v2.34.1
    pullPolicy: IfNotPresent
