// Copyright 2026 Defense Unicorns
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

// Code generated by kubernetes-fluent-client, do not edit manually

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ClusterConfig is the cluster-scoped singleton resource for UDS cluster configuration.
// Only one instance is allowed, named "uds-cluster-config".
type ClusterConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ClusterConfigSpec   `json:"spec"`
	Status            ClusterConfigStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ClusterConfigList holds a list of ClusterConfig resources.
type ClusterConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterConfig `json:"items"`
}

type ClusterConfigSpec struct {
	// Attributes provides optional metadata about the cluster.
	Attributes *ClusterConfigAttributes `json:"attributes,omitempty"`
	// Networking holds optional CIDR overrides for kube-apiserver and nodes.
	Networking *ClusterConfigNetworking `json:"networking,omitempty"`
	// CABundle configures the cluster CA certificate bundle.
	CABundle *ClusterConfigCABundle `json:"caBundle,omitempty"`
	// Expose configures the domains cluster services are exposed on. Required.
	Expose ClusterConfigExpose `json:"expose"`
	// Policy configures cluster-wide policy settings. Required.
	Policy ClusterConfigPolicy `json:"policy"`
}

// ClusterConfigAttributes provides optional metadata about the cluster.
type ClusterConfigAttributes struct {
	// ClusterName is a friendly name to associate with the UDS cluster.
	ClusterName *string `json:"clusterName,omitempty"`
	// Tags are labels to apply to the UDS cluster.
	Tags []string `json:"tags,omitempty"`
}

// ClusterConfigNetworking holds optional CIDR overrides used to generate network policies.
type ClusterConfigNetworking struct {
	// KubeApiCIDR is the CIDR range for Kubernetes control plane nodes.
	KubeApiCIDR *string `json:"kubeApiCIDR,omitempty"`
	// KubeNodeCIDRs are the CIDRs for all Kubernetes nodes.
	KubeNodeCIDRs []string `json:"kubeNodeCIDRs,omitempty"`
}

// ClusterConfigCABundle configures the cluster CA certificate bundle.
type ClusterConfigCABundle struct {
	// Certs is the base64-encoded PEM bundle of user-provided CA certificates.
	Certs *string `json:"certs,omitempty"`
	// IncludeDoDCerts controls whether DoD CA certificates are included in the bundle.
	IncludeDoDCerts *bool `json:"includeDoDCerts,omitempty"`
	// IncludePublicCerts controls whether public CA certificates are included in the bundle.
	IncludePublicCerts *bool `json:"includePublicCerts,omitempty"`
}

// ClusterConfigExpose configures the domains cluster services are exposed on.
type ClusterConfigExpose struct {
	// Domain is the domain all cluster services are exposed on. Required.
	Domain string `json:"domain"`
	// AdminDomain is the domain for admin gateway services. Defaults to "admin.<domain>".
	AdminDomain *string `json:"adminDomain,omitempty"`
}

// ClusterConfigPolicy configures cluster-wide policy settings.
type ClusterConfigPolicy struct {
	// AllowAllNsExemptions controls whether UDS Exemption CRs may live in any namespace.
	AllowAllNsExemptions bool `json:"allowAllNsExemptions"`
}

// ConfigPhase represents the reconciliation phase of the ClusterConfig.
type ConfigPhase string

const (
	ConfigPhasePending ConfigPhase = "Pending"
	ConfigPhaseReady   ConfigPhase = "Ready"
	ConfigPhaseFailed  ConfigPhase = "Failed"
)

// ClusterConfigStatus holds the observed state of the ClusterConfig.
type ClusterConfigStatus struct {
	// Phase is the current reconciliation phase.
	Phase *ConfigPhase `json:"phase,omitempty"`
	// ObservedGeneration is the metadata.generation that was last successfully processed.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}
