// Copyright 2026 Defense Unicorns
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

// Code generated by kubernetes-fluent-client, do not edit manually

package v1alpha1

import (
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// SchemeGroupVersion is the group/version for the uds.dev API.
var SchemeGroupVersion = schema.GroupVersion{Group: "uds.dev", Version: "v1alpha1"}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UDSPackage is the top-level Kubernetes resource type for a UDS Package.
type UDSPackage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              Spec          `json:"spec,omitempty"`
	Status            PackageStatus `json:"status,omitempty"`
}

// UDSPackageList holds a list of Package resources.
type UDSPackageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UDSPackage `json:"items"`
}

// PackageStatus is an alias for the generated StatusClass type.
type PackageStatus = StatusClass

type Spec struct {
	// CA bundle configuration for the package
	CABundle *CABundle `json:"caBundle,omitempty"`
	// Create Service or Pod Monitor configurations
	Monitor []Monitor `json:"monitor,omitempty"`
	// Network configuration for the package
	Network *Network `json:"network,omitempty"`
	// Create SSO client configurations
	Sso []Sso `json:"sso,omitempty"`
}

// CA bundle configuration for the package
type CABundle struct {
	// ConfigMap configuration for CA bundle
	ConfigMap *ConfigMap `json:"configMap,omitempty"`
}

// ConfigMap configuration for CA bundle
type ConfigMap struct {
	// Additional annotations to apply to the generated ConfigMap (default: {})
	Annotations map[string]string `json:"annotations,omitempty"`
	// The key name inside the ConfigMap (default: ca-bundle.pem)
	Key *string `json:"key,omitempty"`
	// Additional labels to apply to the generated ConfigMap (default: {})
	Labels map[string]string `json:"labels,omitempty"`
	// The name of the ConfigMap to create (default: uds-trust-bundle)
	Name *string `json:"name,omitempty"`
}

type Monitor struct {
	// Authorization settings.
	Authorization *Authorization `json:"authorization,omitempty"`
	// A description of this monitor entry, this will become part of the ServiceMonitor name
	Description *string `json:"description,omitempty"`
	// The protocol for Prometheus to use if a scrape returns a blank, unparsable, or otherwise
	// invalid Content-Type
	FallbackScrapeProtocol *FallbackScrapeProtocol `json:"fallbackScrapeProtocol,omitempty"`
	// The type of monitor to create; PodMonitor or ServiceMonitor. ServiceMonitor is the
	// default.
	Kind *Kind `json:"kind,omitempty"`
	// HTTP path from which to scrape for metrics, defaults to `/metrics`
	Path *string `json:"path,omitempty"`
	// Selector for Pods targeted by the selected Services (so the NetworkPolicy can be
	// generated correctly). Defaults to `selector` when not specified.
	PodSelector map[string]string `json:"podSelector,omitempty"`
	// The port name for the serviceMonitor
	PortName string `json:"portName"`
	// Selector for Services that expose metrics to scrape
	Selector map[string]string `json:"selector"`
	// The service targetPort. This is required so the NetworkPolicy can be generated correctly.
	TargetPort float64 `json:"targetPort"`
}

// Authorization settings.
type Authorization struct {
	// Selects a key of a Secret in the namespace that contains the credentials for
	// authentication.
	Credentials Credentials `json:"credentials"`
	// Defines the authentication type. The value is case-insensitive. "Basic" is not a
	// supported value. Default: "Bearer"
	Type *string `json:"type,omitempty"`
}

// Selects a key of a Secret in the namespace that contains the credentials for
// authentication.
type Credentials struct {
	// The key of the secret to select from. Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent. More info:
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// Network configuration for the package
type Network struct {
	// Allow specific traffic (namespace will have a default-deny policy)
	Allow []Allow `json:"allow,omitempty"`
	// Expose a service on an Istio Gateway
	Expose []Expose `json:"expose,omitempty"`
	// Service Mesh configuration for the package
	ServiceMesh *ServiceMesh `json:"serviceMesh,omitempty"`
}

type Allow struct {
	// A description of the policy, this will become part of the policy name
	Description *string `json:"description,omitempty"`
	// The direction of the traffic
	Direction Direction `json:"direction"`
	// The labels to apply to the policy
	Labels map[string]string `json:"labels,omitempty"`
	// Deprecated: use selector
	PodLabels map[string]string `json:"podLabels,omitempty"`
	// The port to allow (protocol is always TCP)
	Port *float64 `json:"port,omitempty"`
	// A list of ports to allow (protocol is always TCP)
	Ports []float64 `json:"ports,omitempty"`
	// Custom generated policy CIDR
	RemoteCIDR *string `json:"remoteCidr,omitempty"`
	// Custom generated remote selector for the policy
	RemoteGenerated *RemoteGenerated `json:"remoteGenerated,omitempty"`
	// Remote host to allow traffic out to
	RemoteHost *string `json:"remoteHost,omitempty"`
	// The remote namespace to allow traffic to/from. Use * or empty string to allow all
	// namespaces
	RemoteNamespace *string `json:"remoteNamespace,omitempty"`
	// Deprecated: use remoteSelector
	RemotePodLabels map[string]string `json:"remotePodLabels,omitempty"`
	// Protocol used for external connection
	RemoteProtocol *RemoteProtocol `json:"remoteProtocol,omitempty"`
	// The remote pod selector labels to allow traffic to/from
	RemoteSelector map[string]string `json:"remoteSelector,omitempty"`
	// The remote service account to restrict incoming traffic from within the remote
	// namespace. Only valid for Ingress rules.
	RemoteServiceAccount *string `json:"remoteServiceAccount,omitempty"`
	// Labels to match pods in the namespace to apply the policy to. Leave empty to apply to all
	// pods in the namespace
	Selector map[string]string `json:"selector,omitempty"`
	// The service account to restrict outgoing traffic from within the package
	// namespace. Only valid for Egress rules.
	ServiceAccount *string `json:"serviceAccount,omitempty"`
}

type Expose struct {
	// Advanced HTTP settings for the route.
	AdvancedHTTP *AdvancedHTTP `json:"advancedHTTP,omitempty"`
	// A description of this expose entry, this will become part of the VirtualService name
	Description *string `json:"description,omitempty"`
	// The domain to expose the service on, only valid for additional gateways (not tenant,
	// admin, or passthrough)
	Domain *string `json:"domain,omitempty"`
	// The name of the gateway to expose the service on (default: tenant)
	Gateway *string `json:"gateway,omitempty"`
	// The hostname to expose the service on
	Host string `json:"host"`
	// Match conditions to be satisfied for the rule to be activated. Not permitted when using
	// the passthrough gateway.
	Match []ExposeMatch `json:"match,omitempty"`
	// Deprecated: use selector
	PodLabels map[string]string `json:"podLabels,omitempty"`
	// The port number to expose
	Port *float64 `json:"port,omitempty"`
	// Selector for Pods targeted by the selected Services (so the NetworkPolicy can be
	// generated correctly).
	Selector map[string]string `json:"selector,omitempty"`
	// The name of the service to expose
	Service *string `json:"service,omitempty"`
	// The service targetPort. This defaults to port and is only required if the service port is
	// different from the target port (so the NetworkPolicy can be generated correctly).
	TargetPort *float64 `json:"targetPort,omitempty"`
	// Uptime monitoring configuration for this exposed service. Presence of checks.paths
	// enables monitoring.
	Uptime *Uptime `json:"uptime,omitempty"`
}

// Advanced HTTP settings for the route.
type AdvancedHTTP struct {
	// Cross-Origin Resource Sharing policy (CORS).
	CorsPolicy *CorsPolicy `json:"corsPolicy,omitempty"`
	// A HTTP rule can either return a direct_response, redirect or forward (default) traffic.
	DirectResponse *DirectResponse `json:"directResponse,omitempty"`
	Headers        *Headers        `json:"headers,omitempty"`
	// Match conditions to be satisfied for the rule to be activated. Not permitted when using
	// the passthrough gateway.
	Match []AdvancedHTTPMatch `json:"match,omitempty"`
	// A HTTP rule can either return a direct_response, redirect or forward (default) traffic.
	Redirect *Redirect `json:"redirect,omitempty"`
	// Retry policy for HTTP requests.
	Retries *Retries `json:"retries,omitempty"`
	// Rewrite HTTP URIs and Authority headers.
	Rewrite *Rewrite `json:"rewrite,omitempty"`
	// Timeout for HTTP requests, default is disabled.
	Timeout *string `json:"timeout,omitempty"`
}

// Cross-Origin Resource Sharing policy (CORS).
type CorsPolicy struct {
	// Indicates whether the caller is allowed to send the actual request (not the preflight)
	// using credentials.
	AllowCredentials *bool `json:"allowCredentials,omitempty"`
	// List of HTTP headers that can be used when requesting the resource.
	AllowHeaders []string `json:"allowHeaders,omitempty"`
	// List of HTTP methods allowed to access the resource.
	AllowMethods []string `json:"allowMethods,omitempty"`
	AllowOrigin  []string `json:"allowOrigin,omitempty"`
	// String patterns that match allowed origins.
	AllowOrigins []AllowOrigin `json:"allowOrigins,omitempty"`
	// A list of HTTP headers that the browsers are allowed to access.
	ExposeHeaders []string `json:"exposeHeaders,omitempty"`
	// Specifies how long the results of a preflight request can be cached.
	MaxAge *string `json:"maxAge,omitempty"`
	// Indicates whether preflight requests not matching the configured allowed origin shouldn't
	// be forwarded to the upstream.
	//
	// Valid Options: FORWARD, IGNORE
	UnmatchedPreflights *UnmatchedPreflights `json:"unmatchedPreflights,omitempty"`
}

type AllowOrigin struct {
	Exact  *string `json:"exact,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
	// [RE2 style regex-based match](https://github.com/google/re2/wiki/Syntax).
	Regex *string `json:"regex,omitempty"`
}

// A HTTP rule can either return a direct_response, redirect or forward (default) traffic.
type DirectResponse struct {
	// Specifies the content of the response body.
	Body *Body `json:"body,omitempty"`
	// Specifies the HTTP response status to be returned.
	Status int64 `json:"status"`
}

// Specifies the content of the response body.
type Body struct {
	// response body as base64 encoded bytes.
	Bytes  *string `json:"bytes,omitempty"`
	String *string `json:"string,omitempty"`
}

type Headers struct {
	Request  *HeaderOp `json:"request,omitempty"`
	Response *HeaderOp `json:"response,omitempty"`
}

type HeaderOp struct {
	Add    map[string]string `json:"add,omitempty"`
	Remove []string          `json:"remove,omitempty"`
	Set    map[string]string `json:"set,omitempty"`
}

type AdvancedHTTPMatch struct {
	// Flag to specify whether the URI matching should be case-insensitive.
	IgnoreURICase *bool `json:"ignoreUriCase,omitempty"`
	// HTTP Method values are case-sensitive and formatted as follows: - `exact: "value"` for
	// exact string match - `prefix: "value"` for prefix-based match - `regex: "value"` for [RE2
	// style regex-based match](https://github.com/google/re2/wiki/Syntax).
	Method *StringMatch `json:"method,omitempty"`
	// The name assigned to a match.
	Name *string `json:"name,omitempty"`
	// Query parameters for matching.
	QueryParams map[string]StringMatch `json:"queryParams,omitempty"`
	// URI to match values are case-sensitive and formatted as follows: - `exact: "value"` for
	// exact string match - `prefix: "value"` for prefix-based match - `regex: "value"` for [RE2
	// style regex-based match](https://github.com/google/re2/wiki/Syntax).
	URI *StringMatch `json:"uri,omitempty"`
}

// StringMatch is a reusable string match type (exact, prefix, or regex).
type StringMatch struct {
	Exact  *string `json:"exact,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
	// [RE2 style regex-based match](https://github.com/google/re2/wiki/Syntax).
	Regex *string `json:"regex,omitempty"`
}

type ExposeMatch struct {
	// Flag to specify whether the URI matching should be case-insensitive.
	IgnoreURICase *bool `json:"ignoreUriCase,omitempty"`
	// HTTP Method values are case-sensitive and formatted as follows: - `exact: "value"` for
	// exact string match - `prefix: "value"` for prefix-based match - `regex: "value"` for [RE2
	// style regex-based match](https://github.com/google/re2/wiki/Syntax).
	Method *StringMatch `json:"method,omitempty"`
	// The name assigned to a match.
	Name *string `json:"name,omitempty"`
	// Query parameters for matching.
	QueryParams map[string]StringMatch `json:"queryParams,omitempty"`
	// URI to match values are case-sensitive and formatted as follows: - `exact: "value"` for
	// exact string match - `prefix: "value"` for prefix-based match - `regex: "value"` for [RE2
	// style regex-based match](https://github.com/google/re2/wiki/Syntax).
	URI *StringMatch `json:"uri,omitempty"`
}

// A HTTP rule can either return a direct_response, redirect or forward (default) traffic.
type Redirect struct {
	// On a redirect, overwrite the Authority/Host portion of the URL with this value.
	Authority *string `json:"authority,omitempty"`
	// On a redirect, dynamically set the port: * FROM_PROTOCOL_DEFAULT: automatically set to 80
	// for HTTP and 443 for HTTPS.
	//
	// Valid Options: FROM_PROTOCOL_DEFAULT, FROM_REQUEST_PORT
	DerivePort *DerivePort `json:"derivePort,omitempty"`
	// On a redirect, overwrite the port portion of the URL with this value.
	Port *int64 `json:"port,omitempty"`
	// On a redirect, Specifies the HTTP status code to use in the redirect response.
	RedirectCode *int64 `json:"redirectCode,omitempty"`
	// On a redirect, overwrite the scheme portion of the URL with this value.
	Scheme *string `json:"scheme,omitempty"`
	// On a redirect, overwrite the Path portion of the URL with this value.
	URI *string `json:"uri,omitempty"`
}

// Retry policy for HTTP requests.
type Retries struct {
	// Number of retries to be allowed for a given request.
	Attempts *int64 `json:"attempts,omitempty"`
	// Specifies the minimum duration between retry attempts.
	Backoff *string `json:"backoff,omitempty"`
	// Timeout per attempt for a given request, including the initial call and any retries.
	PerTryTimeout *string `json:"perTryTimeout,omitempty"`
	// Flag to specify whether the retries should ignore previously tried hosts during retry.
	RetryIgnorePreviousHosts *bool `json:"retryIgnorePreviousHosts,omitempty"`
	// Specifies the conditions under which retry takes place.
	RetryOn *string `json:"retryOn,omitempty"`
	// Flag to specify whether the retries should retry to other localities.
	RetryRemoteLocalities *bool `json:"retryRemoteLocalities,omitempty"`
}

// Rewrite HTTP URIs and Authority headers.
type Rewrite struct {
	// rewrite the Authority/Host header with this value.
	Authority *string `json:"authority,omitempty"`
	// rewrite the path (or the prefix) portion of the URI with this value.
	URI *string `json:"uri,omitempty"`
	// rewrite the path portion of the URI with the specified regex.
	URIRegexRewrite *URIRegexRewrite `json:"uriRegexRewrite,omitempty"`
}

// rewrite the path portion of the URI with the specified regex.
type URIRegexRewrite struct {
	// [RE2 style regex-based match](https://github.com/google/re2/wiki/Syntax).
	Match *string `json:"match,omitempty"`
	// The string that should replace into matching portions of original URI.
	Rewrite *string `json:"rewrite,omitempty"`
}

// Uptime monitoring configuration for this exposed service. Presence of checks.paths
// enables monitoring.
type Uptime struct {
	// HTTP probe checks configuration for blackbox-exporter. Defining paths enables uptime
	// monitoring.
	Checks *Checks `json:"checks,omitempty"`
}

// HTTP probe checks configuration for blackbox-exporter. Defining paths enables uptime
// monitoring.
type Checks struct {
	// List of paths to check for uptime monitoring, appended to the host.
	Paths []string `json:"paths"`
}

// Service Mesh configuration for the package
type ServiceMesh struct {
	// Set the service mesh mode for this package (namespace), defaults to ambient
	Mode *Mode `json:"mode,omitempty"`
}

type Sso struct {
	// This URL will be used for every binding to both the SP's Assertion Consumer and Single
	// Logout Services.
	AdminURL *string `json:"adminUrl,omitempty"`
	// Always list this client in the Account UI, even if the user does not have an active
	// session.
	AlwaysDisplayInConsole *bool `json:"alwaysDisplayInConsole,omitempty"`
	// Specifies attributes for the client.
	Attributes map[string]string `json:"attributes,omitempty"`
	// Default URL to use when the auth server needs to redirect or link back to the client.
	BaseURL *string `json:"baseUrl,omitempty"`
	// The client authenticator type
	ClientAuthenticatorType *ClientAuthenticatorType `json:"clientAuthenticatorType,omitempty"`
	// The client identifier registered with the identity provider.
	ClientID string `json:"clientId"`
	// Default client scopes
	DefaultClientScopes []string `json:"defaultClientScopes,omitempty"`
	// A description for the client, can be a URL to an image to replace the login logo
	Description *string `json:"description,omitempty"`
	// Labels to match pods to automatically protect with authservice. Leave empty to disable
	// authservice protection
	EnableAuthserviceSelector map[string]string `json:"enableAuthserviceSelector,omitempty"`
	// Whether the SSO client is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// The client SSO group type
	Groups *Groups `json:"groups,omitempty"`
	// Specifies display name of the client
	Name string `json:"name"`
	// Specifies the protocol of the client, either 'openid-connect' or 'saml'
	Protocol *Protocol `json:"protocol,omitempty"`
	// Protocol Mappers to configure on the client
	ProtocolMappers []ProtocolMapper `json:"protocolMappers,omitempty"`
	// Defines whether the client requires a client secret for authentication
	PublicClient *bool `json:"publicClient,omitempty"`
	// Valid URI pattern a browser can redirect to after a successful login. Simple wildcards
	// are allowed such as 'https://unicorns.uds.dev/*'
	RedirectUris []string `json:"redirectUris,omitempty"`
	// Root URL appended to relative URLs
	RootURL *string `json:"rootUrl,omitempty"`
	// The OAuth/OIDC client secret value sent to Keycloak.
	Secret *string `json:"secret,omitempty"`
	// Deprecated: use secretConfig.annotations
	SecretAnnotations map[string]string `json:"secretAnnotations,omitempty"`
	// Configuration for the generated Kubernetes Secret
	SecretConfig *SecretConfig `json:"secretConfig,omitempty"`
	// Deprecated: use secretConfig.labels
	SecretLabels map[string]string `json:"secretLabels,omitempty"`
	// Deprecated: use secretConfig.name
	SecretName *string `json:"secretName,omitempty"`
	// Deprecated: use secretConfig.template
	SecretTemplate map[string]string `json:"secretTemplate,omitempty"`
	// Enables the client credentials grant based authentication via OpenID Connect protocol.
	ServiceAccountsEnabled *bool `json:"serviceAccountsEnabled,omitempty"`
	// Enables the standard OpenID Connect redirect based authentication with authorization code.
	StandardFlowEnabled *bool `json:"standardFlowEnabled,omitempty"`
	// Allowed CORS origins.
	WebOrigins []string `json:"webOrigins,omitempty"`
}

// The client SSO group type
type Groups struct {
	// List of groups allowed to access the client
	AnyOf []string `json:"anyOf,omitempty"`
}

type ProtocolMapper struct {
	// Configuration options for the mapper.
	Config map[string]string `json:"config,omitempty"`
	// Whether user consent is required for this mapper
	ConsentRequired *bool `json:"consentRequired,omitempty"`
	// Name of the mapper
	Name string `json:"name"`
	// Protocol of the mapper
	Protocol Protocol `json:"protocol"`
	// Protocol Mapper type of the mapper
	ProtocolMapper string `json:"protocolMapper"`
}

// Configuration for the generated Kubernetes Secret
type SecretConfig struct {
	// Additional annotations to apply to the generated secret
	Annotations map[string]string `json:"annotations,omitempty"`
	// Additional labels to apply to the generated secret
	Labels map[string]string `json:"labels,omitempty"`
	// The name of the secret to store the client secret
	Name *string `json:"name,omitempty"`
	// A template for the generated secret
	Template map[string]string `json:"template,omitempty"`
}

type StatusClass struct {
	AuthorizationPolicyCount *int64              `json:"authorizationPolicyCount,omitempty"`
	AuthserviceClients       []AuthserviceClient `json:"authserviceClients,omitempty"`
	// Status conditions following Kubernetes-style conventions
	Conditions []Condition `json:"conditions,omitempty"`
	Endpoints  []string    `json:"endpoints,omitempty"`
	// The current service mesh mode for this package
	MeshMode           *Mode    `json:"meshMode,omitempty"`
	Monitors           []string `json:"monitors,omitempty"`
	NetworkPolicyCount *int64   `json:"networkPolicyCount,omitempty"`
	ObservedGeneration *int64   `json:"observedGeneration,omitempty"`
	Phase              *Phase   `json:"phase,omitempty"`
	Probes             []string `json:"probes,omitempty"`
	RetryAttempt       *int64   `json:"retryAttempt,omitempty"`
	SsoClients         []string `json:"ssoClients,omitempty"`
}

type AuthserviceClient struct {
	ClientID string            `json:"clientId"`
	Selector map[string]string `json:"selector,omitempty"`
}

type Condition struct {
	// The last time the condition transitioned from one status to another
	LastTransitionTime time.Time `json:"lastTransitionTime"`
	// A human-readable message indicating details about the transition
	Message string `json:"message"`
	// Represents the .metadata.generation that the condition was set based upon
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// A programmatic identifier indicating the reason for the condition's last transition
	Reason string `json:"reason"`
	// Status of the condition, one of True, False, Unknown
	Status StatusEnum `json:"status"`
	// Type of condition in CamelCase or in foo.example.com/CamelCase format
	Type string `json:"type"`
}

// The protocol for Prometheus to use if a scrape returns a blank, unparsable, or otherwise
// invalid Content-Type
type FallbackScrapeProtocol string

const (
	OpenMetricsText001 FallbackScrapeProtocol = "OpenMetricsText0.0.1"
	OpenMetricsText100 FallbackScrapeProtocol = "OpenMetricsText1.0.0"
	PrometheusProto    FallbackScrapeProtocol = "PrometheusProto"
	PrometheusText004  FallbackScrapeProtocol = "PrometheusText0.0.4"
	PrometheusText100  FallbackScrapeProtocol = "PrometheusText1.0.0"
)

// The type of monitor to create; PodMonitor or ServiceMonitor. ServiceMonitor is the
// default.
type Kind string

const (
	PodMonitor     Kind = "PodMonitor"
	ServiceMonitor Kind = "ServiceMonitor"
)

// The direction of the traffic
type Direction string

const (
	Egress  Direction = "Egress"
	Ingress Direction = "Ingress"
)

// Custom generated remote selector for the policy
type RemoteGenerated string

const (
	Anywhere       RemoteGenerated = "Anywhere"
	CloudMetadata  RemoteGenerated = "CloudMetadata"
	IntraNamespace RemoteGenerated = "IntraNamespace"
	KubeAPI        RemoteGenerated = "KubeAPI"
	KubeNodes      RemoteGenerated = "KubeNodes"
)

// Protocol used for external connection
type RemoteProtocol string

const (
	HTTP RemoteProtocol = "HTTP"
	TLS  RemoteProtocol = "TLS"
)

// Indicates whether preflight requests not matching the configured allowed origin shouldn't
// be forwarded to the upstream.
//
// Valid Options: FORWARD, IGNORE
type UnmatchedPreflights string

const (
	Forward     UnmatchedPreflights = "FORWARD"
	Ignore      UnmatchedPreflights = "IGNORE"
	Unspecified UnmatchedPreflights = "UNSPECIFIED"
)

// On a redirect, dynamically set the port: * FROM_PROTOCOL_DEFAULT: automatically set to 80
// for HTTP and 443 for HTTPS.
//
// Valid Options: FROM_PROTOCOL_DEFAULT, FROM_REQUEST_PORT
type DerivePort string

const (
	FromProtocolDefault DerivePort = "FROM_PROTOCOL_DEFAULT"
	FromRequestPort     DerivePort = "FROM_REQUEST_PORT"
)

// Set the service mesh mode for this package (namespace), defaults to ambient
//
// The current service mesh mode for this package
type Mode string

const (
	Ambient Mode = "ambient"
	Sidecar Mode = "sidecar"
)

// The client authenticator type
type ClientAuthenticatorType string

const (
	ClientJwt    ClientAuthenticatorType = "client-jwt"
	ClientSecret ClientAuthenticatorType = "client-secret"
)

// Specifies the protocol of the client, either 'openid-connect' or 'saml'
//
// Protocol of the mapper
type Protocol string

const (
	OpenidConnect Protocol = "openid-connect"
	Saml          Protocol = "saml"
)

// Status of the condition, one of True, False, Unknown
type StatusEnum string

const (
	ConditionFalse   StatusEnum = "False"
	ConditionTrue    StatusEnum = "True"
	ConditionUnknown StatusEnum = "Unknown"
)

type Phase string

const (
	PhaseFailed        Phase = "Failed"
	PhasePending       Phase = "Pending"
	PhaseReady         Phase = "Ready"
	PhaseRemovalFailed Phase = "RemovalFailed"
	PhaseRemoving      Phase = "Removing"
	PhaseRetrying      Phase = "Retrying"
)
