// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/applyconfigurations/uds/v1alpha1"
	typedudsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/clientset/versioned/typed/uds/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterConfig implements ClusterConfigInterface
type fakeClusterConfig struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterConfig, *v1alpha1.ClusterConfigList, *udsv1alpha1.ClusterConfigApplyConfiguration]
	Fake *FakeUdsV1alpha1
}

func newFakeClusterConfig(fake *FakeUdsV1alpha1, namespace string) typedudsv1alpha1.ClusterConfigInterface {
	return &fakeClusterConfig{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterConfig, *v1alpha1.ClusterConfigList, *udsv1alpha1.ClusterConfigApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("clusterconfig"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterConfig"),
			func() *v1alpha1.ClusterConfig { return &v1alpha1.ClusterConfig{} },
			func() *v1alpha1.ClusterConfigList { return &v1alpha1.ClusterConfigList{} },
			func(dst, src *v1alpha1.ClusterConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterConfigList) []*v1alpha1.ClusterConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterConfigList, items []*v1alpha1.ClusterConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
