// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/applyconfigurations/uds/v1alpha1"
	typedudsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/clientset/versioned/typed/uds/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeUDSPackages implements UDSPackageInterface
type fakeUDSPackages struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.UDSPackage, *v1alpha1.UDSPackageList, *udsv1alpha1.UDSPackageApplyConfiguration]
	Fake *FakeUdsV1alpha1
}

func newFakeUDSPackages(fake *FakeUdsV1alpha1, namespace string) typedudsv1alpha1.UDSPackageInterface {
	return &fakeUDSPackages{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.UDSPackage, *v1alpha1.UDSPackageList, *udsv1alpha1.UDSPackageApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("udspackages"),
			v1alpha1.SchemeGroupVersion.WithKind("UDSPackage"),
			func() *v1alpha1.UDSPackage { return &v1alpha1.UDSPackage{} },
			func() *v1alpha1.UDSPackageList { return &v1alpha1.UDSPackageList{} },
			func(dst, src *v1alpha1.UDSPackageList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.UDSPackageList) []*v1alpha1.UDSPackage { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.UDSPackageList, items []*v1alpha1.UDSPackage) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
