# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: vector
component:
  charts:
    - name: uds-vector-config
      namespace: vector
      local:
        path: ../chart
    - name: vector
      namespace: vector
      helmRepository:
        url: https://helm.vector.dev
        name: vector
        version: 0.52.0
      valuesFiles:
        - ../values/values.yaml
