# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if and (hasKey .Values.podDisruptionBudget "minAvailable") (hasKey .Values.podDisruptionBudget "maxUnavailable") }}
{{- fail "Cannot set both 'podDisruptionBudget.minAvailable' and 'podDisruptionBudget.maxUnavailable'." }}
{{- end }}
{{- if and .Values.autoscaling.enabled (ne .Values.podDisruptionBudget.enabled false) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  {{- omit .Values.podDisruptionBudget "enabled" | toYaml | nindent 2 }}
{{- end }}
