# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: uds-keycloak-uptime
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: uds-identity-uptime
      rules:
        - record: uds:keycloak:up
          labels:
            uds_layer: identity-authorization
            uds_component: keycloak
          expr: |
            (max(statefulset:up{statefulset="keycloak", namespace="keycloak"}) or on() vector(0))
            and on()
            (kube_state_metrics:up == 1)

        - record: uds:keycloak_waypoint:up
          labels:
            uds_layer: identity-authorization
            uds_component: keycloak_waypoint
          expr: |
            (max(deployment:up{deployment="keycloak-waypoint", namespace="keycloak"}) or on() vector(0))
            and on()
            (kube_state_metrics:up == 1)

        - record: uds:keycloak_endpoint:up
          labels:
            uds_layer: identity-authorization
            uds_component: keycloak_sso_endpoint
          expr: min(probe_success{job="probe/keycloak/uds-sso-tenant-uptime"})
        - record: uds:keycloak_admin_endpoint:up
          labels:
            uds_layer: identity-authorization
            uds_component: keycloak_admin_endpoint
          expr: min(probe_success{job="probe/keycloak/uds-keycloak-admin-uptime"})
{{- end }}
