# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

crds:
  enabled: false
grafana:
  enabled: false
  forceDeployDashboards: true
kube-state-metrics:
  # Enable scraping of istio-specific namespace labels
  metricLabelsAllowlist:
    - namespaces=[istio-injection,istio.io/dataplane-mode]
nameOverride: kube-prometheus-stack
nodeExporter:
  jobLabel: jobLabel
  operatingSystems:
    darwin:
      enabled: false
    linux:
      enabled: false
  serviceMonitor:
    interval: ""
prometheus:
  serviceMonitor:
    selfMonitor: true
  # Enables "zarf connect prometheus"
  service:
    labels:
      zarf.dev/connect-name: prometheus
    annotations:
      zarf.dev/connect-description: "Directly connect to the Prometheus HTTP service"
  prometheusSpec:
    podMetadata:
      labels:
        app: prometheus
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    resources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 512Mi
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
    enableRemoteWriteReceiver: true # enable Prometheus remote write receiver (needed by loki ruler for recording rules)
    volumes:
      - name: ca-certs
        configMap:
          name: uds-trust-bundle
          optional: true
    volumeMounts:
      # Kube Prometheus Stack is a Go based image and accepts this `/etc/ssl/certs/ca-bundle.pem` path
      # based on https://go.dev/src/crypto/x509/root_linux.go
      - name: ca-certs
        mountPath: /etc/ssl/certs/ca-bundle.pem
        subPath: ca-bundle.pem
        readOnly: true
prometheus-node-exporter:
  containerSecurityContext:
    readOnlyRootFilesystem: true
  hostNetwork: false
  hostPID: false
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
prometheusOperator:
  # Kubelet healthprobes on FIPS nodes fail when this is set to 1.3
  tls:
    tlsMinVersion: VersionTLS12
  admissionWebhooks:
    patch:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 128Mi
  prometheusConfigReloader:
    enableProbe:
      false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
alertmanager:
  alertmanagerSpec:
    scheme: "http"
    volumes:
      - name: ca-certs
        configMap:
          name: uds-trust-bundle
          optional: true
    volumeMounts:
      - name: ca-certs
        mountPath: /etc/ssl/certs/ca-bundle.pem
        subPath: ca-bundle.pem
        readOnly: true
  # Enables "zarf connect alertmanager"
  service:
    labels:
      zarf.dev/connect-name: alertmanager
    annotations:
      zarf.dev/connect-description: "Directly connect to the Alertmanager HTTP service"
## UDS Core uptime recording rules
additionalPrometheusRulesMap:
  uds-identity-uptime:
    groups:
      - name: uds-identity-uptime
        rules:
          - record: uds:keycloak:up
            labels:
              uds_layer: identity-authorization
              uds_component: keycloak
            expr: clamp_max(kube_statefulset_status_replicas_available{statefulset="keycloak", namespace="keycloak"}, 1)
          - record: uds:keycloak_waypoint:up
            labels:
              uds_layer: identity-authorization
              uds_component: keycloak_waypoint
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="keycloak-waypoint", namespace="keycloak"}, 1)
          - record: uds:keycloak_endpoint:up
            labels:
              uds_layer: identity-authorization
              uds_component: keycloak_endpoint
            expr: min(probe_success{job="probe/keycloak/uds-sso-tenant-uptime"})
          - record: uds:keycloak_admin_endpoint:up
            labels:
              uds_layer: identity-authorization
              uds_component: keycloak_admin_endpoint
            expr: min(probe_success{job="probe/keycloak/uds-keycloak-admin-uptime"})
          - record: uds:authservice:up
            labels:
              uds_layer: identity-authorization
              uds_component: authservice
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="authservice", namespace="authservice"}, 1)
  uds-base-uptime:
    groups:
      - name: uds-base-uptime
        rules:
          - record: uds:pepr_admission:up
            labels:
              uds_layer: base
              uds_component: pepr_admission
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="pepr-uds-core", namespace="pepr-system"}, 1)
          - record: uds:pepr_watcher:up
            labels:
              uds_layer: base
              uds_component: pepr_watcher
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="pepr-uds-core-watcher", namespace="pepr-system"}, 1)
          - record: uds:istiod:up
            labels:
              uds_layer: base
              uds_component: istiod
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="istiod", namespace="istio-system"}, 1)
          - record: uds:istio_cni:up
            labels:
              uds_layer: base
              uds_component: istio_cni
            expr: kube_daemonset_status_number_ready{daemonset="istio-cni-node", namespace="istio-system"} >= bool kube_daemonset_status_desired_number_scheduled{daemonset="istio-cni-node", namespace="istio-system"}
          - record: uds:admin_ingressgateway:up
            labels:
              uds_layer: base
              uds_component: admin_ingressgateway
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="admin-ingressgateway", namespace="istio-admin-gateway"}, 1)
          - record: uds:ztunnel:up
            labels:
              uds_layer: base
              uds_component: ztunnel
            expr: kube_daemonset_status_number_ready{daemonset="ztunnel", namespace="istio-system"} >= bool kube_daemonset_status_desired_number_scheduled{daemonset="ztunnel", namespace="istio-system"}
          - record: uds:tenant_ingressgateway:up
            labels:
              uds_layer: base
              uds_component: tenant_ingressgateway
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="tenant-ingressgateway", namespace="istio-tenant-gateway"}, 1)
  uds-monitoring-uptime:
    groups:
      - name: uds-monitoring-uptime
        rules:
          - record: uds:prometheus:up
            labels:
              uds_layer: monitoring
              uds_component: prometheus
            expr: clamp_max(kube_statefulset_status_replicas_available{statefulset="prometheus-kube-prometheus-stack-prometheus", namespace="monitoring"}, 1)
          - record: uds:alertmanager:up
            labels:
              uds_layer: monitoring
              uds_component: alertmanager
            expr: clamp_max(kube_statefulset_status_replicas_available{statefulset="alertmanager-kube-prometheus-stack-alertmanager", namespace="monitoring"}, 1)
          - record: uds:grafana:up
            labels:
              uds_layer: monitoring
              uds_component: grafana
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="grafana", namespace="grafana"}, 1)
          - record: uds:blackbox_exporter:up
            labels:
              uds_layer: monitoring
              uds_component: blackbox_exporter
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="prometheus-blackbox-exporter", namespace="monitoring"}, 1)
  uds-logging-uptime:
    groups:
      - name: uds-logging-uptime
        rules:
          - record: uds:loki:up
            labels:
              uds_layer: logging
              uds_component: loki
            expr: clamp_max(kube_statefulset_status_replicas_available{statefulset="loki", namespace="loki"}, 1)
          - record: uds:vector:up
            labels:
              uds_layer: logging
              uds_component: vector
            expr: kube_daemonset_status_number_ready{daemonset="vector", namespace="vector"} >= bool kube_daemonset_status_desired_number_scheduled{daemonset="vector", namespace="vector"}
  uds-runtime-security-uptime:
    groups:
      - name: uds-runtime-security-uptime
        rules:
          - record: uds:falco:up
            labels:
              uds_layer: runtime-security
              uds_component: falco
            expr: kube_daemonset_status_number_ready{daemonset="falco", namespace="falco"} >= bool kube_daemonset_status_desired_number_scheduled{daemonset="falco", namespace="falco"}
          - record: uds:falcosidekick:up
            labels:
              uds_layer: runtime-security
              uds_component: falcosidekick
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="falcosidekick", namespace="falco"}, 1)
  uds-backup-restore-uptime:
    groups:
      - name: uds-backup-restore-uptime
        rules:
          - record: uds:velero:up
            labels:
              uds_layer: backup-restore
              uds_component: velero
            expr: clamp_max(kube_deployment_status_replicas_available{deployment="velero", namespace="velero"}, 1)
  uds-core-uptime:
    groups:
      - name: uds-core-uptime
        rules:
          - record: uds:core:up
            labels:
              uds_layer: core
              uds_component: core
            expr: uds:keycloak_endpoint:up * on() uds:keycloak:up * on() uds:keycloak_waypoint:up * on() uds:tenant_ingressgateway:up * on() uds:ztunnel:up
## Create default rules for monitoring the cluster
##
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8sContainerCpuUsageSecondsTotal: true
    k8sContainerMemoryCache: true
    k8sContainerMemoryRss: true
    k8sContainerMemorySwap: true
    k8sContainerResource: true
    k8sContainerMemoryWorkingSetBytes: true
    k8sPodOwner: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    # @lulaStart 708ffa00-49aa-4bba-9969-051d849fa6d1
    kubernetesApps: true
    # @lulaEnd 708ffa00-49aa-4bba-9969-051d849fa6d1
    kubernetesResources: true
    # @lulaStart 4f5bcf8b-5e01-4ddd-8d6e-63da5eedf2f9
    kubernetesStorage: true
    # @lulaEnd 4f5bcf8b-5e01-4ddd-8d6e-63da5eedf2f9
    kubernetesSystem: true
    kubeSchedulerAlerting: true
    kubeSchedulerRecording: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
    windows: true
