# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: uds-velero-uptime
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: kube-prometheus-stack-prometheus
spec:
  groups:
    - name: uds-backup-restore-uptime
      rules:
        - record: uds:velero:up
          labels:
            uds_layer: backup-restore
            uds_component: velero
          expr: clamp_max(kube_deployment_status_replicas_available{deployment="velero", namespace="velero"}, 1)
{{- end }}
