# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: registry1.dso.mil/ironbank/opensource/keycloak/keycloak-fips
  tag: "26.6.2-fips"
podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
configImage: registry1.dso.mil/ironbank/opensource/defenseunicorns/uds/uds-identity-config:0.29.0

migrations:
  deleteGeneratedTrustStore: true
  # Enabled temporarily for the 26.5.7 -> 26.6.1 upgrade where the Keycloak user id changed
  # Can be safely disabled during the next Keycloak minor version upgrade or sooner
  upgradePermissions: true
