# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: cgr.dev/defenseunicorns.com/metrics-server-fips
  tag: "0.8.1"
