# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: uds-operator-config
component:
  charts:
    - name: uds-operator-config
      namespace: pepr-system
      local:
        path: uds-operator-config
      valuesFiles:
        - uds-operator-config/values.yaml
  actions:
    onDeploy:
      after:
        - description: "Ensure Istio Ambient is enabled for Pepr"
          cmd: |
            echo "Setting Ambient mode for pepr-system..."
            ./zarf tools kubectl label namespace pepr-system "istio.io/dataplane-mode"="ambient" --overwrite

            echo "Disabling istio-injection on pepr-system..."
            ./zarf tools kubectl label namespace pepr-system istio-injection=disabled --overwrite
