# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: uds-exemptions
component:
  charts:
    - name: uds-exemptions
      namespace: uds-policy-exemptions
      local:
        path: uds-exemptions
      valuesFiles:
        - uds-exemptions/values.yaml
