# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfPackageConfig
metadata:
  name: pepr
components:
  - name: uds-crds
    import:
      paths:
        - uds-crds.yaml

  - name: uds-operator-config
    import:
      paths:
        - uds-operator-config.yaml

  - name: pepr-uds-core
    import:
      paths:
        - pepr-uds-core.yaml

  - name: uds-exemptions
    import:
      paths:
        - uds-exemptions.yaml
