# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfPackageConfig
metadata:
  name: pepr
components:
  - name: uds-crds
    import:
      local:
        - path: ./uds-crds.yaml

  - name: uds-operator-config
    import:
      local:
        - path: ./uds-operator-config.yaml

  - name: pepr-uds-core
    import:
      local:
        - path: ./pepr-uds-core.yaml

  - name: uds-exemptions
    import:
      local:
        - path: ./uds-exemptions.yaml
