// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	applyconfigurationsudsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/applyconfigurations/uds/v1alpha1"
	scheme "github.com/defenseunicorns/uds-core/src/go-controller/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterConfigsGetter has a method to return a ClusterConfigInterface.
// A group's client should implement this interface.
type ClusterConfigsGetter interface {
	ClusterConfigs(namespace string) ClusterConfigInterface
}

// ClusterConfigInterface has methods to work with ClusterConfig resources.
type ClusterConfigInterface interface {
	Create(ctx context.Context, clusterConfig *udsv1alpha1.ClusterConfig, opts v1.CreateOptions) (*udsv1alpha1.ClusterConfig, error)
	Update(ctx context.Context, clusterConfig *udsv1alpha1.ClusterConfig, opts v1.UpdateOptions) (*udsv1alpha1.ClusterConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterConfig *udsv1alpha1.ClusterConfig, opts v1.UpdateOptions) (*udsv1alpha1.ClusterConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*udsv1alpha1.ClusterConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*udsv1alpha1.ClusterConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *udsv1alpha1.ClusterConfig, err error)
	Apply(ctx context.Context, clusterConfig *applyconfigurationsudsv1alpha1.ClusterConfigApplyConfiguration, opts v1.ApplyOptions) (result *udsv1alpha1.ClusterConfig, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterConfig *applyconfigurationsudsv1alpha1.ClusterConfigApplyConfiguration, opts v1.ApplyOptions) (result *udsv1alpha1.ClusterConfig, err error)
	ClusterConfigExpansion
}

// clusterConfigs implements ClusterConfigInterface
type clusterConfigs struct {
	*gentype.ClientWithListAndApply[*udsv1alpha1.ClusterConfig, *udsv1alpha1.ClusterConfigList, *applyconfigurationsudsv1alpha1.ClusterConfigApplyConfiguration]
}

// newClusterConfigs returns a ClusterConfigs
func newClusterConfigs(c *ClusterV1alpha1Client, namespace string) *clusterConfigs {
	return &clusterConfigs{
		gentype.NewClientWithListAndApply[*udsv1alpha1.ClusterConfig, *udsv1alpha1.ClusterConfigList, *applyconfigurationsudsv1alpha1.ClusterConfigApplyConfiguration](
			"clusterconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *udsv1alpha1.ClusterConfig { return &udsv1alpha1.ClusterConfig{} },
			func() *udsv1alpha1.ClusterConfigList { return &udsv1alpha1.ClusterConfigList{} },
		),
	}
}
