// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated typed clients.
package v1alpha1
