// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	applyconfigurationsudsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/applyconfigurations/uds/v1alpha1"
	scheme "github.com/defenseunicorns/uds-core/src/go-controller/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// UDSPackagesGetter has a method to return a UDSPackageInterface.
// A group's client should implement this interface.
type UDSPackagesGetter interface {
	UDSPackages(namespace string) UDSPackageInterface
}

// UDSPackageInterface has methods to work with UDSPackage resources.
type UDSPackageInterface interface {
	Create(ctx context.Context, uDSPackage *udsv1alpha1.UDSPackage, opts v1.CreateOptions) (*udsv1alpha1.UDSPackage, error)
	Update(ctx context.Context, uDSPackage *udsv1alpha1.UDSPackage, opts v1.UpdateOptions) (*udsv1alpha1.UDSPackage, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, uDSPackage *udsv1alpha1.UDSPackage, opts v1.UpdateOptions) (*udsv1alpha1.UDSPackage, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*udsv1alpha1.UDSPackage, error)
	List(ctx context.Context, opts v1.ListOptions) (*udsv1alpha1.UDSPackageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *udsv1alpha1.UDSPackage, err error)
	Apply(ctx context.Context, uDSPackage *applyconfigurationsudsv1alpha1.UDSPackageApplyConfiguration, opts v1.ApplyOptions) (result *udsv1alpha1.UDSPackage, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, uDSPackage *applyconfigurationsudsv1alpha1.UDSPackageApplyConfiguration, opts v1.ApplyOptions) (result *udsv1alpha1.UDSPackage, err error)
	UDSPackageExpansion
}

// uDSPackages implements UDSPackageInterface
type uDSPackages struct {
	*gentype.ClientWithListAndApply[*udsv1alpha1.UDSPackage, *udsv1alpha1.UDSPackageList, *applyconfigurationsudsv1alpha1.UDSPackageApplyConfiguration]
}

// newUDSPackages returns a UDSPackages
func newUDSPackages(c *UdsV1alpha1Client, namespace string) *uDSPackages {
	return &uDSPackages{
		gentype.NewClientWithListAndApply[*udsv1alpha1.UDSPackage, *udsv1alpha1.UDSPackageList, *applyconfigurationsudsv1alpha1.UDSPackageApplyConfiguration](
			"udspackages",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *udsv1alpha1.UDSPackage { return &udsv1alpha1.UDSPackage{} },
			func() *udsv1alpha1.UDSPackageList { return &udsv1alpha1.UDSPackageList{} },
		),
	}
}
