// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// UDSPackageListerExpansion allows custom methods to be added to
// UDSPackageLister.
type UDSPackageListerExpansion interface{}
