// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterConfigListerExpansion allows custom methods to be added to
// ClusterConfigLister.
type ClusterConfigListerExpansion interface{}

// ClusterConfigNamespaceListerExpansion allows custom methods to be added to
// ClusterConfigNamespaceLister.
type ClusterConfigNamespaceListerExpansion interface{}

// UDSPackageListerExpansion allows custom methods to be added to
// UDSPackageLister.
type UDSPackageListerExpansion interface{}

// UDSPackageNamespaceListerExpansion allows custom methods to be added to
// UDSPackageNamespaceLister.
type UDSPackageNamespaceListerExpansion interface{}
