// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// UDSPackageLister helps list UDSPackages.
// All objects returned here must be treated as read-only.
type UDSPackageLister interface {
	// List lists all UDSPackages in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*udsv1alpha1.UDSPackage, err error)
	// UDSPackages returns an object that can list and get UDSPackages.
	UDSPackages(namespace string) UDSPackageNamespaceLister
	UDSPackageListerExpansion
}

// uDSPackageLister implements the UDSPackageLister interface.
type uDSPackageLister struct {
	listers.ResourceIndexer[*udsv1alpha1.UDSPackage]
}

// NewUDSPackageLister returns a new UDSPackageLister.
func NewUDSPackageLister(indexer cache.Indexer) UDSPackageLister {
	return &uDSPackageLister{listers.New[*udsv1alpha1.UDSPackage](indexer, udsv1alpha1.Resource("udspackage"))}
}

// UDSPackages returns an object that can list and get UDSPackages.
func (s *uDSPackageLister) UDSPackages(namespace string) UDSPackageNamespaceLister {
	return uDSPackageNamespaceLister{listers.NewNamespaced[*udsv1alpha1.UDSPackage](s.ResourceIndexer, namespace)}
}

// UDSPackageNamespaceLister helps list and get UDSPackages.
// All objects returned here must be treated as read-only.
type UDSPackageNamespaceLister interface {
	// List lists all UDSPackages in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*udsv1alpha1.UDSPackage, err error)
	// Get retrieves the UDSPackage from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*udsv1alpha1.UDSPackage, error)
	UDSPackageNamespaceListerExpansion
}

// uDSPackageNamespaceLister implements the UDSPackageNamespaceLister
// interface.
type uDSPackageNamespaceLister struct {
	listers.ResourceIndexer[*udsv1alpha1.UDSPackage]
}
