# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: ClusterConfig
metadata:
  name: uds-cluster-config
  labels:
    {{- include "uds-operator-config.labels" . | nindent 4 }}
spec:
  {{- if or .Values.cluster.attributes.clusterName .Values.cluster.attributes.clusterTags }}
  attributes:
    {{- if .Values.cluster.attributes.clusterName }}
    clusterName: {{ .Values.cluster.attributes.clusterName | quote }}
    {{- end }}
    {{- if .Values.cluster.attributes.clusterTags }}
    tags:
      {{- toYaml .Values.cluster.attributes.clusterTags | nindent 6 }}
    {{- end }}
  {{- end }}
  caBundle:
    {{- if .Values.cluster.caBundle.certs }}
    certs: {{ .Values.cluster.caBundle.certs | quote }}
    {{- end }}
    includeDoDCerts: {{ .Values.cluster.caBundle.includeDoDCerts | default false | toString | eq "true" }}
    includePublicCerts: {{ .Values.cluster.caBundle.includePublicCerts | default false | toString | eq "true" }}
  {{- if or .Values.cluster.networking.kubeApiCIDR .Values.cluster.networking.kubeNodeCIDRs }}
  networking:
    {{- if .Values.cluster.networking.kubeApiCIDR }}
    kubeApiCIDR: {{ .Values.cluster.networking.kubeApiCIDR | quote }}
    {{- end }}
    {{- if .Values.cluster.networking.kubeNodeCIDRs }}
    kubeNodeCIDRs:
      {{- toYaml .Values.cluster.networking.kubeNodeCIDRs | nindent 6 }}
    {{- end }}
  {{- end }}
  expose:
    domain: {{ .Values.cluster.expose.domain | quote }}
    {{- if .Values.cluster.expose.adminDomain }}
    adminDomain: {{ .Values.cluster.expose.adminDomain | quote }}
    {{- else }}
    adminDomain: "admin.{{ .Values.cluster.expose.domain }}"
    {{- end }}
  policy:
    allowAllNsExemptions: {{ .Values.cluster.policy.allowAllNsExemptions }}
