# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial


apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  sso:
    - name: Grafana
      clientId: uds-core-admin-grafana
      redirectUris:
        {{- $admin := .Values.udsAdminDomain | default (.Values.adminDomain | default (printf "admin.%s" .Values.domain)) }}
        - "https://grafana.{{ $admin }}/login/generic_oauth"
        - "https://grafana.{{ $admin }}/login"
      {{- if .Values.sso.groups }}
      groups:
        anyOf:
        {{- range .Values.sso.groups }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}


  monitor:
    - selector:
        app.kubernetes.io/name: grafana
      targetPort: 3000
      portName: service
      description: Metrics

  network:
    serviceMesh:
      mode: ambient
    # @lulaStart 506992d2-64cf-4fb3-95de-40a8ad127626
    expose:
      - service: grafana
        selector:
          app.kubernetes.io/name: grafana
        host: grafana
        gateway: admin
        port: 80
        targetPort: 3000
        annotations:
          uds.dev/title: "Grafana"
          uds.dev/icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzNTEiIGhlaWdodD0iMzY1IiB2aWV3Qm94PSIwIDAgMzUxIDM2NSI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMTc1LjUiIHkxPSIzMCUiIHgyPSIxNzUuNSIgeTI9Ijk5JSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPjxzdG9wIG9mZnNldD0iMCIgc3RvcC1jb2xvcj0iI0YwNUEyOCIvPjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iI0ZCQ0EwQSIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxwYXRoIGZpbGw9InVybCgjZykiIGQ9Ik0zNDIsMTYxLjJjLTAuNi02LjEtMS42LTEzLjEtMy42LTIwLjljLTItNy43LTUtMTYuMi05LjQtMjVjLTQuNC04LjgtMTAuMS0xNy45LTE3LjUtMjYuOCBjLTIuOS0zLjUtNi4xLTYuOS05LjUtMTAuMmM1LjEtMjAuMy02LjItMzcuOS02LjItMzcuOWMtMTkuNS0xLjItMzEuOSw2LjEtMzYuNSw5LjRjLTAuOC0wLjMtMS41LTAuNy0yLjMtMSBjLTMuMy0xLjMtNi43LTIuNi0xMC4zLTMuN2MtMy41LTEuMS03LjEtMi4xLTEwLjgtM2MtMy43LTAuOS03LjQtMS42LTExLjItMi4yYy0wLjctMC4xLTEuMy0wLjItMi0wLjMgYy04LjUtMjcuMi0zMi45LTM4LjYtMzIuOS0zOC42Yy0yNy4zLDE3LjMtMzIuNCw0MS41LTMyLjQsNDEuNXMtMC4xLDAuNS0wLjMsMS40Yy0xLjUsMC40LTMsMC45LTQuNSwxLjNjLTIuMSwwLjYtNC4yLDEuNC02LjIsMi4yIGMtMi4xLDAuOC00LjEsMS42LTYuMiwyLjVjLTQuMSwxLjgtOC4yLDMuOC0xMi4yLDZjLTMuOSwyLjItNy43LDQuNi0xMS40LDcuMWMtMC41LTAuMi0xLTAuNC0xLTAuNGMtMzcuOC0xNC40LTcxLjMsMi45LTcxLjMsMi45IGMtMy4xLDQwLjIsMTUuMSw2NS41LDE4LjcsNzAuMWMtMC45LDIuNS0xLjcsNS0yLjUsNy41Yy0yLjgsOS4xLTQuOSwxOC40LTYuMiwyOC4xYy0wLjIsMS40LTAuNCwyLjgtMC41LDQuMiBDMTguOCwxOTIuNyw4LjUsMjI4LDguNSwyMjhjMjkuMSwzMy41LDYzLjEsMzUuNiw2My4xLDM1LjZjMCwwLDAuMS0wLjEsMC4xLTAuMWM0LjMsNy43LDkuMywxNSwxNC45LDIxLjljMi40LDIuOSw0LjgsNS42LDcuNCw4LjMgYy0xMC42LDMwLjQsMS41LDU1LjYsMS41LDU1LjZjMzIuNCwxLjIsNTMuNy0xNC4yLDU4LjItMTcuN2MzLjIsMS4xLDYuNSwyLjEsOS44LDIuOWMxMCwyLjYsMjAuMiw0LjEsMzAuNCw0LjUgYzIuNSwwLjEsNS4xLDAuMiw3LjYsMC4xbDEuMiwwbDAuOCwwbDEuNiwwbDEuNi0wLjFsMCwwLjFjMTUuMywyMS44LDQyLjEsMjQuOSw0Mi4xLDI0LjljMTkuMS0yMC4xLDIwLjItNDAuMSwyMC4yLTQ0LjRsMCwwIGMwLDAsMC0wLjEsMC0wLjNjMC0wLjQsMC0wLjYsMC0wLjZsMCwwYzAtMC4zLDAtMC42LDAtMC45YzQtMi44LDcuOC01LjgsMTEuNC05LjFjNy42LTYuOSwxNC4zLTE0LjgsMTkuOS0yMy4zIGMwLjUtMC44LDEtMS42LDEuNS0yLjRjMjEuNiwxLjIsMzYuOS0xMy40LDM2LjktMTMuNGMtMy42LTIyLjUtMTYuNC0zMy41LTE5LjEtMzUuNmwwLDBjMCwwLTAuMS0wLjEtMC4zLTAuMiBjLTAuMi0wLjEtMC4yLTAuMi0wLjItMC4yYzAsMCwwLDAsMCwwYy0wLjEtMC4xLTAuMy0wLjItMC41LTAuM2MwLjEtMS40LDAuMi0yLjcsMC4zLTQuMWMwLjItMi40LDAuMi00LjksMC4yLTcuM2wwLTEuOGwwLTAuOSBsMC0wLjVjMC0wLjYsMC0wLjQsMC0wLjZsLTAuMS0xLjVsLTAuMS0yYzAtMC43LTAuMS0xLjMtMC4yLTEuOWMtMC4xLTAuNi0wLjEtMS4zLTAuMi0xLjlsLTAuMi0xLjlsLTAuMy0xLjkgYy0wLjQtMi41LTAuOC00LjktMS40LTcuNGMtMi4zLTkuNy02LjEtMTguOS0xMS0yNy4yYy01LTguMy0xMS4yLTE1LjYtMTguMy0yMS44Yy03LTYuMi0xNC45LTExLjItMjMuMS0xNC45IGMtOC4zLTMuNy0xNi45LTYuMS0yNS41LTcuMmMtNC4zLTAuNi04LjYtMC44LTEyLjktMC43bC0xLjYsMGwtMC40LDBjLTAuMSwwLTAuNiwwLTAuNSwwbC0wLjcsMGwtMS42LDAuMWMtMC42LDAtMS4yLDAuMS0xLjcsMC4xIGMtMi4yLDAuMi00LjQsMC41LTYuNSwwLjljLTguNiwxLjYtMTYuNyw0LjctMjMuOCw5Yy03LjEsNC4zLTEzLjMsOS42LTE4LjMsMTUuNmMtNSw2LTguOSwxMi43LTExLjYsMTkuNmMtMi43LDYuOS00LjIsMTQuMS00LjYsMjEgYy0wLjEsMS43LTAuMSwzLjUtMC4xLDUuMmMwLDAuNCwwLDAuOSwwLDEuM2wwLjEsMS40YzAuMSwwLjgsMC4xLDEuNywwLjIsMi41YzAuMywzLjUsMSw2LjksMS45LDEwLjFjMS45LDYuNSw0LjksMTIuNCw4LjYsMTcuNCBjMy43LDUsOC4yLDkuMSwxMi45LDEyLjRjNC43LDMuMiw5LjgsNS41LDE0LjgsN2M1LDEuNSwxMCwyLjEsMTQuNywyLjFjMC42LDAsMS4yLDAsMS43LDBjMC4zLDAsMC42LDAsMC45LDBjMC4zLDAsMC42LDAsMC45LTAuMSBjMC41LDAsMS0wLjEsMS41LTAuMWMwLjEsMCwwLjMsMCwwLjQtMC4xbDAuNS0wLjFjMC4zLDAsMC42LTAuMSwwLjktMC4xYzAuNi0wLjEsMS4xLTAuMiwxLjctMC4zYzAuNi0wLjEsMS4xLTAuMiwxLjYtMC40IGMxLjEtMC4yLDIuMS0wLjYsMy4xLTAuOWMyLTAuNyw0LTEuNSw1LjctMi40YzEuOC0wLjksMy40LTIsNS0zYzAuNC0wLjMsMC45LTAuNiwxLjMtMWMxLjYtMS4zLDEuOS0zLjcsMC42LTUuMyBjLTEuMS0xLjQtMy4xLTEuOC00LjctMC45Yy0wLjQsMC4yLTAuOCwwLjQtMS4yLDAuNmMtMS40LDAuNy0yLjgsMS4zLTQuMywxLjhjLTEuNSwwLjUtMy4xLDAuOS00LjcsMS4yYy0wLjgsMC4xLTEuNiwwLjItMi41LDAuMyBjLTAuNCwwLTAuOCwwLjEtMS4zLDAuMWMtMC40LDAtMC45LDAtMS4yLDBjLTAuNCwwLTAuOCwwLTEuMiwwYy0wLjUsMC0xLDAtMS41LTAuMWMwLDAtMC4zLDAtMC4xLDBsLTAuMiwwbC0wLjMsMCBjLTAuMiwwLTAuNSwwLTAuNy0wLjFjLTAuNS0wLjEtMC45LTAuMS0xLjQtMC4yYy0zLjctMC41LTcuNC0xLjYtMTAuOS0zLjJjLTMuNi0xLjYtNy0zLjgtMTAuMS02LjZjLTMuMS0yLjgtNS44LTYuMS03LjktOS45IGMtMi4xLTMuOC0zLjYtOC00LjMtMTIuNGMtMC4zLTIuMi0wLjUtNC41LTAuNC02LjdjMC0wLjYsMC4xLTEuMiwwLjEtMS44YzAsMC4yLDAtMC4xLDAtMC4xbDAtMC4ybDAtMC41YzAtMC4zLDAuMS0wLjYsMC4xLTAuOSBjMC4xLTEuMiwwLjMtMi40LDAuNS0zLjZjMS43LTkuNiw2LjUtMTksMTMuOS0yNi4xYzEuOS0xLjgsMy45LTMuNCw2LTQuOWMyLjEtMS41LDQuNC0yLjgsNi44LTMuOWMyLjQtMS4xLDQuOC0yLDcuNC0yLjcgYzIuNS0wLjcsNS4xLTEuMSw3LjgtMS40YzEuMy0wLjEsMi42LTAuMiw0LTAuMmMwLjQsMCwwLjYsMCwwLjksMGwxLjEsMGwwLjcsMGMwLjMsMCwwLDAsMC4xLDBsMC4zLDBsMS4xLDAuMSBjMi45LDAuMiw1LjcsMC42LDguNSwxLjNjNS42LDEuMiwxMS4xLDMuMywxNi4yLDYuMWMxMC4yLDUuNywxOC45LDE0LjUsMjQuMiwyNS4xYzIuNyw1LjMsNC42LDExLDUuNSwxNi45YzAuMiwxLjUsMC40LDMsMC41LDQuNSBsMC4xLDEuMWwwLjEsMS4xYzAsMC40LDAsMC44LDAsMS4xYzAsMC40LDAsMC44LDAsMS4xbDAsMWwwLDEuMWMwLDAuNy0wLjEsMS45LTAuMSwyLjZjLTAuMSwxLjYtMC4zLDMuMy0wLjUsNC45IGMtMC4yLDEuNi0wLjUsMy4yLTAuOCw0LjhjLTAuMywxLjYtMC43LDMuMi0xLjEsNC43Yy0wLjgsMy4xLTEuOCw2LjItMyw5LjNjLTIuNCw2LTUuNiwxMS44LTkuNCwxNy4xIGMtNy43LDEwLjYtMTguMiwxOS4yLTMwLjIsMjQuN2MtNiwyLjctMTIuMyw0LjctMTguOCw1LjdjLTMuMiwwLjYtNi41LDAuOS05LjgsMWwtMC42LDBsLTAuNSwwbC0xLjEsMGwtMS42LDBsLTAuOCwwIGMwLjQsMC0wLjEsMC0wLjEsMGwtMC4zLDBjLTEuOCwwLTMuNS0wLjEtNS4zLTAuM2MtNy0wLjUtMTMuOS0xLjgtMjAuNy0zLjdjLTYuNy0xLjktMTMuMi00LjYtMTkuNC03LjggYy0xMi4zLTYuNi0yMy40LTE1LjYtMzItMjYuNWMtNC4zLTUuNC04LjEtMTEuMy0xMS4yLTE3LjRjLTMuMS02LjEtNS42LTEyLjYtNy40LTE5LjFjLTEuOC02LjYtMi45LTEzLjMtMy40LTIwLjFsLTAuMS0xLjNsMC0wLjMgbDAtMC4zbDAtMC42bDAtMS4xbDAtMC4zbDAtMC40bDAtMC44bDAtMS42bDAtMC4zYzAsMCwwLDAuMSwwLTAuMWwwLTAuNmMwLTAuOCwwLTEuNywwLTIuNWMwLjEtMy4zLDAuNC02LjgsMC44LTEwLjIgYzAuNC0zLjQsMS02LjksMS43LTEwLjNjMC43LTMuNCwxLjUtNi44LDIuNS0xMC4yYzEuOS02LjcsNC4zLTEzLjIsNy4xLTE5LjNjNS43LTEyLjIsMTMuMS0yMy4xLDIyLTMxLjhjMi4yLTIuMiw0LjUtNC4yLDYuOS02LjIgYzIuNC0xLjksNC45LTMuNyw3LjUtNS40YzIuNS0xLjcsNS4yLTMuMiw3LjktNC42YzEuMy0wLjcsMi43LTEuNCw0LjEtMmMwLjctMC4zLDEuNC0wLjYsMi4xLTAuOWMwLjctMC4zLDEuNC0wLjYsMi4xLTAuOSBjMi44LTEuMiw1LjctMi4yLDguNy0zLjFjMC43LTAuMiwxLjUtMC40LDIuMi0wLjdjMC43LTAuMiwxLjUtMC40LDIuMi0wLjZjMS41LTAuNCwzLTAuOCw0LjUtMS4xYzAuNy0wLjIsMS41LTAuMywyLjMtMC41IGMwLjgtMC4yLDEuNS0wLjMsMi4zLTAuNWMwLjgtMC4xLDEuNS0wLjMsMi4zLTAuNGwxLjEtMC4ybDEuMi0wLjJjMC44LTAuMSwxLjUtMC4yLDIuMy0wLjNjMC45LTAuMSwxLjctMC4yLDIuNi0wLjMgYzAuNy0wLjEsMS45LTAuMiwyLjYtMC4zYzAuNS0wLjEsMS4xLTAuMSwxLjYtMC4ybDEuMS0wLjFsMC41LTAuMWwwLjYsMGMwLjktMC4xLDEuNy0wLjEsMi42LTAuMmwxLjMtMC4xYzAsMCwwLjUsMCwwLjEsMGwwLjMsMCBsMC42LDBjMC43LDAsMS41LTAuMSwyLjItMC4xYzIuOS0wLjEsNS45LTAuMSw4LjgsMGM1LjgsMC4yLDExLjUsMC45LDE3LDEuOWMxMS4xLDIuMSwyMS41LDUuNiwzMSwxMC4zIGM5LjUsNC42LDE3LjksMTAuMywyNS4zLDE2LjVjMC41LDAuNCwwLjksMC44LDEuNCwxLjJjMC40LDAuNCwwLjksMC44LDEuMywxLjJjMC45LDAuOCwxLjcsMS42LDIuNiwyLjRjMC45LDAuOCwxLjcsMS42LDIuNSwyLjQgYzAuOCwwLjgsMS42LDEuNiwyLjQsMi41YzMuMSwzLjMsNiw2LjYsOC42LDEwYzUuMiw2LjcsOS40LDEzLjUsMTIuNywxOS45YzAuMiwwLjQsMC40LDAuOCwwLjYsMS4yYzAuMiwwLjQsMC40LDAuOCwwLjYsMS4yIGMwLjQsMC44LDAuOCwxLjYsMS4xLDIuNGMwLjQsMC44LDAuNywxLjUsMS4xLDIuM2MwLjMsMC44LDAuNywxLjUsMSwyLjNjMS4yLDMsMi40LDUuOSwzLjMsOC42YzEuNSw0LjQsMi42LDguMywzLjUsMTEuNyBjMC4zLDEuNCwxLjYsMi4zLDMsMi4xYzEuNS0wLjEsMi42LTEuMywyLjYtMi44QzM0Mi42LDE3MC40LDM0Mi41LDE2Ni4xLDM0MiwxNjEuMnoiLz48L3N2Zz4="
        {{- if .Values.uptime.enabled }}
        uptime:
          checks:
            paths:
              - /healthz # monitor the healthz path as all other paths redirect to keycloak
        {{- end }}
    # @lulaEnd 506992d2-64cf-4fb3-95de-40a8ad127626

    allow:
      # Egress allowed to Loki
      - direction: Egress
        selector:
          app.kubernetes.io/name: grafana
        remoteNamespace: loki
        remoteSelector:
          app.kubernetes.io/name: loki
        description: "Loki Datasource"
        port: 8080

      # Egress allowed to Prometheus
      - direction: Egress
        selector:
          app.kubernetes.io/name: grafana
        remoteNamespace: monitoring
        remoteSelector:
          app.kubernetes.io/name: prometheus
        description: "Prometheus Datasource"
        port: 9090

      # Egress allowed to Alertmanager
      - direction: Egress
        selector:
          app.kubernetes.io/name: grafana
        remoteNamespace: monitoring
        remoteSelector:
          app.kubernetes.io/name: alertmanager
        description: "Alertmanager Datasource"
        port: 9093

      # Egress must be allowed to the external facing Keycloak endpoint
      - direction: Egress
        selector:
          app.kubernetes.io/name: grafana
        remoteSelector:
          app: tenant-ingressgateway
        remoteNamespace: istio-tenant-gateway
        description: "SSO Provider"

      # Egress allowed to KubeAPI
      - direction: Egress
        selector:
          app.kubernetes.io/name: grafana
        remoteGenerated: KubeAPI
        description: "Datasources Watcher"

      {{- if eq (include "grafana.postgresql.config" .) "true" }}
      - description: "Postgresql access"
        direction: Egress
        selector:
          app.kubernetes.io/name: grafana
        port: {{ .Values.postgresql.port }}
        {{- if .Values.postgresql.internal.enabled }}
        remoteSelector:
          {{- .Values.postgresql.internal.remoteSelector | toYaml | nindent 10 }}
        remoteNamespace: {{ .Values.postgresql.internal.remoteNamespace }}
        {{- else if .Values.postgresql.egressCidr }}
        remoteCidr: {{ .Values.postgresql.egressCidr }}
        {{- else }}
        remoteGenerated: Anywhere
        {{- end }}
      {{- end }}

      # HA for Grafana
      - direction: Ingress
        remoteGenerated: IntraNamespace
        ports:
          - 3000
      - direction: Egress
        remoteGenerated: IntraNamespace
        ports:
          - 3000

      # Custom rules for additional networking access
      {{- with .Values.additionalNetworkAllow }}
      {{ toYaml . | nindent 6 }}
      {{- end }}

