# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: uds-grafana-uptime
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: kube-prometheus-stack-prometheus
spec:
  groups:
    - name: uds-monitoring-grafana-uptime
      rules:
        - record: uds:grafana:up
          labels:
            uds_layer: monitoring
            uds_component: grafana
          expr: clamp_max(kube_deployment_status_replicas_available{deployment="grafana", namespace="grafana"}, 1)
{{- end }}
