// This file is auto-generated by kubernetes-fluent-client, do not edit manually

import { GenericKind, RegisterKind } from "kubernetes-fluent-client";

export class Gateway extends GenericKind {
  /**
   * Configuration affecting edge load balancer. See more details at:
   * https://istio.io/docs/reference/config/networking/gateway.html
   */
  spec?: Spec;
  status?: { [key: string]: unknown };
}

/**
 * Configuration affecting edge load balancer. See more details at:
 * https://istio.io/docs/reference/config/networking/gateway.html
 */
export interface Spec {
  /**
   * One or more labels that indicate a specific set of pods/VMs on which this gateway
   * configuration should be applied.
   */
  selector?: { [key: string]: string };
  /**
   * A list of server specifications.
   */
  servers?: Server[];
}

export interface Server {
  /**
   * The ip or the Unix domain socket to which the listener should be bound to.
   */
  bind?: string;
  defaultEndpoint?: string;
  /**
   * One or more hosts exposed by this gateway.
   */
  hosts: string[];
  /**
   * An optional name of the server, when set must be unique across all servers.
   */
  name?: string;
  /**
   * The Port on which the proxy should listen for incoming connections.
   */
  port: Port;
  /**
   * Set of TLS related options that govern the server's behavior.
   */
  tls?: TLS;
}

/**
 * The Port on which the proxy should listen for incoming connections.
 */
export interface Port {
  /**
   * Label assigned to the port.
   */
  name: string;
  /**
   * A valid non-negative integer port number.
   */
  number: number;
  /**
   * The protocol exposed on the port.
   */
  protocol: string;
  targetPort?: number;
}

/**
 * Set of TLS related options that govern the server's behavior.
 */
export interface TLS {
  /**
   * REQUIRED if mode is `MUTUAL` or `OPTIONAL_MUTUAL`.
   */
  caCertificates?: string;
  /**
   * Optional: If specified, only support the specified cipher list.
   */
  cipherSuites?: string[];
  /**
   * For gateways running on Kubernetes, the name of the secret that holds the TLS certs
   * including the CA certificates.
   */
  credentialName?: string;
  /**
   * If set to true, the load balancer will send a 301 redirect for all http connections,
   * asking the clients to use HTTPS.
   */
  httpsRedirect?: boolean;
  /**
   * Optional: Maximum TLS protocol version.
   */
  maxProtocolVersion?: ProtocolVersion;
  /**
   * Optional: Minimum TLS protocol version.
   */
  minProtocolVersion?: ProtocolVersion;
  /**
   * Optional: Indicates whether connections to this port should be secured using TLS.
   */
  mode?: Mode;
  /**
   * REQUIRED if mode is `SIMPLE` or `MUTUAL`.
   */
  privateKey?: string;
  /**
   * REQUIRED if mode is `SIMPLE` or `MUTUAL`.
   */
  serverCertificate?: string;
  /**
   * A list of alternate names to verify the subject identity in the certificate presented by
   * the client.
   */
  subjectAltNames?: string[];
  /**
   * An optional list of hex-encoded SHA-256 hashes of the authorized client certificates.
   */
  verifyCertificateHash?: string[];
  /**
   * An optional list of base64-encoded SHA-256 hashes of the SPKIs of authorized client
   * certificates.
   */
  verifyCertificateSpki?: string[];
}

/**
 * Optional: Maximum TLS protocol version.
 *
 * Optional: Minimum TLS protocol version.
 */
export enum ProtocolVersion {
  TLSAuto = "TLS_AUTO",
  Tlsv10 = "TLSV1_0",
  Tlsv11 = "TLSV1_1",
  Tlsv12 = "TLSV1_2",
  Tlsv13 = "TLSV1_3",
}

/**
 * Optional: Indicates whether connections to this port should be secured using TLS.
 */
export enum Mode {
  AutoPassthrough = "AUTO_PASSTHROUGH",
  IstioMutual = "ISTIO_MUTUAL",
  Mutual = "MUTUAL",
  OptionalMutual = "OPTIONAL_MUTUAL",
  Passthrough = "PASSTHROUGH",
  Simple = "SIMPLE",
}

RegisterKind(Gateway, {
  group: "networking.istio.io",
  version: "v1beta1",
  kind: "Gateway",
});
