# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

additionalNetworkAllow: []
kubevirt:
  enabled: true
  configuration: {}
  extraValues: {}
  infra:
    nodePlacement: {}
  workloads:
    nodePlacement: {}
cdi:
  enabled: true
  scratchSpaceStorageClass: ""
  infra:
    nodeSelector: {}
  workload:
    nodeSelector: {}
image:
  registry: ""
  tag: ""
