# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: kubevirt
  namespace: {{ .Release.Namespace }}
spec:
  network:
    serviceMesh:
      mode: ambient
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Ingress
        remoteNamespace: monitoring
        remoteSelector:
          app: prometheus
        selector:
          prometheus.kubevirt.io: "true"
        port: 8443
        description: Metrics

      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Ingress
        selector:
          kubevirt.io: virt-api
        remoteGenerated: Anywhere

      - direction: Egress
        selector:
          kubevirt.io: virt-operator
        remoteGenerated: KubeAPI
        description: "virt-operator to KubeAPI"

      - direction: Egress
        selector:
          kubevirt.io: virt-operator-strategy-dumper
        remoteGenerated: KubeAPI
        description: "virt-operator-strategy-dumper to KubeAPI"

      - direction: Egress
        selector:
          kubevirt.io: virt-api
        remoteGenerated: KubeAPI
        description: "virt-api to KubeAPI"

      - direction: Egress
        selector:
          kubevirt.io: virt-controller
        remoteGenerated: KubeAPI
        description: "virt-controller to KubeAPI"

      - direction: Egress
        selector:
          kubevirt.io: virt-handler
        remoteGenerated: KubeAPI
        description: "virt-handler to KubeAPI"

      - direction: Egress
        selector:
          kubevirt.io: virt-exportproxy
        remoteGenerated: KubeAPI
        description: "virt-exportproxy to KubeAPI"

      {{- range .Values.additionalNetworkAllow }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
      {{- end }}
