# Copyright 2025-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfPackageConfig
metadata:
  name: falco
components:
  - name: falco
    import:
      local:
        - path: ./flavors/falco-upstream.yaml
        - path: ./flavors/falco-registry1.yaml
        - path: ./flavors/falco-unicorn.yaml
