# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: kube-prometheus-stack
  description: "Install kube-prometheus-stack using the helm chart https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack"
component:
  target:
    flavor: registry1
  import:
    paths:
      - common/kube-prometheus-stack.yaml
  charts:
    - name: kube-prometheus-stack
      valuesFiles:
        - values/registry1/kube-prometheus-stack.yaml
  images:
    - name: registry1.dso.mil/ironbank/opensource/prometheus/node-exporter:v1.11.1
    - name: registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-operator:v0.90.1
    - name: registry1.dso.mil/ironbank/opensource/kubernetes/kube-state-metrics:v2.18.0
    - name: registry1.dso.mil/ironbank/opensource/prometheus/alertmanager:v0.32.1
    - name: registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-config-reloader:v0.90.1
    - name: registry1.dso.mil/ironbank/opensource/prometheus/prometheus:v3.11.3
    - name: registry1.dso.mil/ironbank/opensource/ingress-nginx/kube-webhook-certgen:v1.6.9
