# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: prometheus-blackbox-exporter
  description: "UDS Core Prometheus Blackbox Exporter"
component:
  target:
    flavor: registry1
  import:
    paths:
      - common/prometheus-blackbox-exporter.yaml
  charts:
    - name: prometheus-blackbox-exporter
      valuesFiles:
        - values/registry1/blackbox-exporter.yaml
  images:
    - name: registry1.dso.mil/ironbank/opensource/prometheus/blackbox_exporter:v0.28.0
    - name: registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-config-reloader:v0.90.1
