# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

kind: ZarfPackageConfig
metadata:
  # @lulaStart ed10edbf-7e7d-4dd4-be96-b19842c75bdc
  name: uds-core-prometheus-stack
  # @lulaEnd ed10edbf-7e7d-4dd4-be96-b19842c75bdc
  description: "UDS Core Prometheus-Stack"

components:
  - name: prometheus-operator-crds
    required: true
    description: "Install kube-prometheus-stack operator crds using the helm chart https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds"
    charts:
      - name: prometheus-operator-crds
        url: https://prometheus-community.github.io/helm-charts
        version: 29.0.0
        namespace: uds-crds
        valuesFiles:
          - "values/crd-values.yaml"

  - name: kube-prometheus-stack
    required: true
    description: "Install kube-prometheus-stack using the helm chart https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack"
    only:
      flavor: upstream
    import:
      path: common
    charts:
      - name: kube-prometheus-stack
        valuesFiles:
          - "values/upstream/kube-prometheus-stack.yaml"
    images:
      - "quay.io/prometheus/node-exporter:v1.11.1-distroless"
      - "quay.io/prometheus-operator/prometheus-operator:v0.91.0"
      - "registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.19.0"
      - "quay.io/prometheus/alertmanager:v0.32.1"
      - "quay.io/prometheus-operator/prometheus-config-reloader:v0.91.0"
      - "quay.io/prometheus/prometheus:v3.11.3"
      - "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.6.9"

  - name: kube-prometheus-stack
    required: true
    description: "Install kube-prometheus-stack using the helm chart https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack"
    only:
      flavor: registry1
    import:
      path: common
    charts:
      - name: kube-prometheus-stack
        valuesFiles:
          - "values/registry1/kube-prometheus-stack.yaml"
    images:
      - "registry1.dso.mil/ironbank/opensource/prometheus/node-exporter:v1.11.1"
      - "registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-operator:v0.91.0"
      - "registry1.dso.mil/ironbank/opensource/kubernetes/kube-state-metrics:v2.19.0"
      - "registry1.dso.mil/ironbank/opensource/prometheus/alertmanager:v0.32.1"
      - "registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-config-reloader:v0.91.0"
      - "registry1.dso.mil/ironbank/opensource/prometheus/prometheus:v3.11.3"
      - "registry1.dso.mil/ironbank/opensource/ingress-nginx/kube-webhook-certgen:v1.6.9"

  - name: kube-prometheus-stack
    required: true
    description: "Install kube-prometheus-stack using the helm chart https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack"
    only:
      flavor: unicorn
    import:
      path: common
    charts:
      - name: kube-prometheus-stack
        valuesFiles:
          - "values/unicorn/kube-prometheus-stack.yaml"
    images:
      - "cgr.dev/defenseunicorns.com/prometheus-node-exporter-fips:1.11.1"
      - "cgr.dev/defenseunicorns.com/prometheus-operator-fips:0.91.0"
      - "cgr.dev/defenseunicorns.com/kube-state-metrics-fips:v2.19.0"
      - "cgr.dev/defenseunicorns.com/prometheus-alertmanager-fips:0.32.1"
      - "cgr.dev/defenseunicorns.com/prometheus-config-reloader-fips:0.91.0"
      - "cgr.dev/defenseunicorns.com/prometheus-fips:3.11.3"
      - "cgr.dev/defenseunicorns.com/kube-webhook-certgen-fips:v1.15.5" # Chainguard provides kube-webhook-certgen from their ingress-nginx package, which follows a different versioning scheme than upstream's ingress-nginx/kube-webhook-certgen

  - name: prometheus-blackbox-exporter
    required: true
    description: "UDS Core Prometheus Blackbox Exporter"
    only:
      flavor: upstream
    import:
      path: common
    charts:
      - name: prometheus-blackbox-exporter
        valuesFiles:
          - "values/upstream/blackbox-exporter.yaml"
    images:
      - "quay.io/prometheus/blackbox-exporter:v0.28.0"
      - "quay.io/prometheus-operator/prometheus-config-reloader:v0.91.0"

  - name: prometheus-blackbox-exporter
    required: true
    description: "UDS Core Prometheus Blackbox Exporter"
    only:
      flavor: registry1
    import:
      path: common
    charts:
      - name: prometheus-blackbox-exporter
        valuesFiles:
          - "values/registry1/blackbox-exporter.yaml"
    images:
      - "registry1.dso.mil/ironbank/opensource/prometheus/blackbox_exporter:v0.28.0"
      - "registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-config-reloader:v0.91.0"

  - name: prometheus-blackbox-exporter
    required: true
    description: "UDS Core Prometheus Blackbox Exporter"
    only:
      flavor: unicorn
    import:
      path: common
    charts:
      - name: prometheus-blackbox-exporter
        valuesFiles:
          - "values/unicorn/blackbox-exporter.yaml"
    images:
      - "cgr.dev/defenseunicorns.com/prometheus-blackbox-exporter-fips:0.28.0"
      - "cgr.dev/defenseunicorns.com/prometheus-config-reloader-fips:0.91.0"
