# Copyright 2025-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Default Zarf values for the Prometheus-Stack package.
kube-prometheus-stack:
  kube-prometheus-stack: {}
  uds-prometheus-config: {}
prometheus-blackbox-exporter:
  prometheus-blackbox-exporter: {}
