# Copyright 2025-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: falco
  description: "Deploy Falco"
component:
  target:
    flavor: registry1
  import:
    paths:
      - ../common/falco.yaml
  charts:
    - name: falco
      valuesFiles:
        - ../values/registry1-values.yaml
  images:
    - name: registry1.dso.mil/ironbank/opensource/falcosecurity/falco:0.43.1
    - name: registry1.dso.mil/ironbank/opensource/falcosecurity/falcosidekick:2.33.0
