# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: vector
  description: "Deploy Vector"
component:
  target:
    flavor: upstream
  import:
    paths:
      - ../common/vector.yaml
  charts:
    - name: vector
      valuesFiles:
        - ../values/upstream-values.yaml
  images:
    - name: timberio/vector:0.55.0-distroless-static
