// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	internal "github.com/defenseunicorns/uds-core/src/go-controller/client/applyconfigurations/internal"
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/applyconfigurations/uds/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=uds.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("AdvancedHTTP"):
		return &udsv1alpha1.AdvancedHTTPApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AdvancedHTTPMatch"):
		return &udsv1alpha1.AdvancedHTTPMatchApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Allow"):
		return &udsv1alpha1.AllowApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AllowOrigin"):
		return &udsv1alpha1.AllowOriginApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Authorization"):
		return &udsv1alpha1.AuthorizationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AuthserviceClient"):
		return &udsv1alpha1.AuthserviceClientApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Body"):
		return &udsv1alpha1.BodyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CABundle"):
		return &udsv1alpha1.CABundleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Checks"):
		return &udsv1alpha1.ChecksApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterConfig"):
		return &udsv1alpha1.ClusterConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterConfigAttributes"):
		return &udsv1alpha1.ClusterConfigAttributesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterConfigCABundle"):
		return &udsv1alpha1.ClusterConfigCABundleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterConfigExpose"):
		return &udsv1alpha1.ClusterConfigExposeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterConfigNetworking"):
		return &udsv1alpha1.ClusterConfigNetworkingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterConfigPolicy"):
		return &udsv1alpha1.ClusterConfigPolicyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterConfigSpec"):
		return &udsv1alpha1.ClusterConfigSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterConfigStatus"):
		return &udsv1alpha1.ClusterConfigStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Condition"):
		return &udsv1alpha1.ConditionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConfigMap"):
		return &udsv1alpha1.ConfigMapApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CorsPolicy"):
		return &udsv1alpha1.CorsPolicyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Credentials"):
		return &udsv1alpha1.CredentialsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DirectResponse"):
		return &udsv1alpha1.DirectResponseApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Expose"):
		return &udsv1alpha1.ExposeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExposeMatch"):
		return &udsv1alpha1.ExposeMatchApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Groups"):
		return &udsv1alpha1.GroupsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HeaderOp"):
		return &udsv1alpha1.HeaderOpApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Headers"):
		return &udsv1alpha1.HeadersApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Monitor"):
		return &udsv1alpha1.MonitorApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Network"):
		return &udsv1alpha1.NetworkApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PackageStatus"):
		return &udsv1alpha1.PackageStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProtocolMapper"):
		return &udsv1alpha1.ProtocolMapperApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Redirect"):
		return &udsv1alpha1.RedirectApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Retries"):
		return &udsv1alpha1.RetriesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Rewrite"):
		return &udsv1alpha1.RewriteApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SecretConfig"):
		return &udsv1alpha1.SecretConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceMesh"):
		return &udsv1alpha1.ServiceMeshApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Spec"):
		return &udsv1alpha1.SpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Sso"):
		return &udsv1alpha1.SsoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("StringMatch"):
		return &udsv1alpha1.StringMatchApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("UDSPackage"):
		return &udsv1alpha1.UDSPackageApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Uptime"):
		return &udsv1alpha1.UptimeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("URIRegexRewrite"):
		return &udsv1alpha1.URIRegexRewriteApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
