# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: apps/v1
kind: Deployment
metadata:
  name: uds-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: uds-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uds-controller
  template:
    metadata:
      labels:
        app: uds-controller
    spec:
      serviceAccountName: uds-controller
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
