# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: cgr.dev
  repository: defenseunicorns.com/prometheus-blackbox-exporter-fips
  tag: 0.28.0

configReloader:
  image:
    registry: cgr.dev
    repository: defenseunicorns.com/prometheus-config-reloader-fips
    tag: 0.91.0
