# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: keycloak
component:
  target:
    flavor: registry1
  import:
    paths:
      - common/keycloak.yaml
  charts:
    - name: keycloak
      valuesFiles:
        - values/registry1-values.yaml
  images:
    - name: registry1.dso.mil/ironbank/opensource/keycloak/keycloak-fips:26.6.1-fips
    - name: registry1.dso.mil/ironbank/opensource/defenseunicorns/uds/uds-identity-config:0.26.1
