# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfPackageConfig
metadata:
  name: keycloak
components:
  - name: keycloak
    import:
      paths:
        - flavors/keycloak-upstream.yaml
        - flavors/keycloak-registry1.yaml
        - flavors/keycloak-unicorn.yaml
