// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// AllowApplyConfiguration represents a declarative configuration of the Allow type for use
// with apply.
type AllowApplyConfiguration struct {
	// A description of the policy, this will become part of the policy name
	Description *string `json:"description,omitempty"`
	// The direction of the traffic
	Direction *udsv1alpha1.Direction `json:"direction,omitempty"`
	// The labels to apply to the policy
	Labels map[string]string `json:"labels,omitempty"`
	// Deprecated: use selector
	PodLabels map[string]string `json:"podLabels,omitempty"`
	// The port to allow (protocol is always TCP)
	Port *float64 `json:"port,omitempty"`
	// A list of ports to allow (protocol is always TCP)
	Ports []float64 `json:"ports,omitempty"`
	// Custom generated policy CIDR
	RemoteCIDR *string `json:"remoteCidr,omitempty"`
	// Custom generated remote selector for the policy
	RemoteGenerated *udsv1alpha1.RemoteGenerated `json:"remoteGenerated,omitempty"`
	// Remote host to allow traffic out to
	RemoteHost *string `json:"remoteHost,omitempty"`
	// The remote namespace to allow traffic to/from. Use * or empty string to allow all
	// namespaces
	RemoteNamespace *string `json:"remoteNamespace,omitempty"`
	// Deprecated: use remoteSelector
	RemotePodLabels map[string]string `json:"remotePodLabels,omitempty"`
	// Protocol used for external connection
	RemoteProtocol *udsv1alpha1.RemoteProtocol `json:"remoteProtocol,omitempty"`
	// The remote pod selector labels to allow traffic to/from
	RemoteSelector map[string]string `json:"remoteSelector,omitempty"`
	// The remote service account to restrict incoming traffic from within the remote
	// namespace. Only valid for Ingress rules.
	RemoteServiceAccount *string `json:"remoteServiceAccount,omitempty"`
	// Labels to match pods in the namespace to apply the policy to. Leave empty to apply to all
	// pods in the namespace
	Selector map[string]string `json:"selector,omitempty"`
	// The service account to restrict outgoing traffic from within the package
	// namespace. Only valid for Egress rules.
	ServiceAccount *string `json:"serviceAccount,omitempty"`
}

// AllowApplyConfiguration constructs a declarative configuration of the Allow type for use with
// apply.
func Allow() *AllowApplyConfiguration {
	return &AllowApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithDescription(value string) *AllowApplyConfiguration {
	b.Description = &value
	return b
}

// WithDirection sets the Direction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direction field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithDirection(value udsv1alpha1.Direction) *AllowApplyConfiguration {
	b.Direction = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *AllowApplyConfiguration) WithLabels(entries map[string]string) *AllowApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *AllowApplyConfiguration) WithPodLabels(entries map[string]string) *AllowApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithPort(value float64) *AllowApplyConfiguration {
	b.Port = &value
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *AllowApplyConfiguration) WithPorts(values ...float64) *AllowApplyConfiguration {
	for i := range values {
		b.Ports = append(b.Ports, values[i])
	}
	return b
}

// WithRemoteCIDR sets the RemoteCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteCIDR field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteCIDR(value string) *AllowApplyConfiguration {
	b.RemoteCIDR = &value
	return b
}

// WithRemoteGenerated sets the RemoteGenerated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteGenerated field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteGenerated(value udsv1alpha1.RemoteGenerated) *AllowApplyConfiguration {
	b.RemoteGenerated = &value
	return b
}

// WithRemoteHost sets the RemoteHost field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteHost field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteHost(value string) *AllowApplyConfiguration {
	b.RemoteHost = &value
	return b
}

// WithRemoteNamespace sets the RemoteNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteNamespace field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteNamespace(value string) *AllowApplyConfiguration {
	b.RemoteNamespace = &value
	return b
}

// WithRemotePodLabels puts the entries into the RemotePodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RemotePodLabels field,
// overwriting an existing map entries in RemotePodLabels field with the same key.
func (b *AllowApplyConfiguration) WithRemotePodLabels(entries map[string]string) *AllowApplyConfiguration {
	if b.RemotePodLabels == nil && len(entries) > 0 {
		b.RemotePodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.RemotePodLabels[k] = v
	}
	return b
}

// WithRemoteProtocol sets the RemoteProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteProtocol field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteProtocol(value udsv1alpha1.RemoteProtocol) *AllowApplyConfiguration {
	b.RemoteProtocol = &value
	return b
}

// WithRemoteSelector puts the entries into the RemoteSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RemoteSelector field,
// overwriting an existing map entries in RemoteSelector field with the same key.
func (b *AllowApplyConfiguration) WithRemoteSelector(entries map[string]string) *AllowApplyConfiguration {
	if b.RemoteSelector == nil && len(entries) > 0 {
		b.RemoteSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.RemoteSelector[k] = v
	}
	return b
}

// WithRemoteServiceAccount sets the RemoteServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteServiceAccount field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteServiceAccount(value string) *AllowApplyConfiguration {
	b.RemoteServiceAccount = &value
	return b
}

// WithSelector puts the entries into the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Selector field,
// overwriting an existing map entries in Selector field with the same key.
func (b *AllowApplyConfiguration) WithSelector(entries map[string]string) *AllowApplyConfiguration {
	if b.Selector == nil && len(entries) > 0 {
		b.Selector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Selector[k] = v
	}
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithServiceAccount(value string) *AllowApplyConfiguration {
	b.ServiceAccount = &value
	return b
}
