// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AuthorizationApplyConfiguration represents a declarative configuration of the Authorization type for use
// with apply.
//
// Authorization settings.
type AuthorizationApplyConfiguration struct {
	// Selects a key of a Secret in the namespace that contains the credentials for
	// authentication.
	Credentials *CredentialsApplyConfiguration `json:"credentials,omitempty"`
	// Defines the authentication type. The value is case-insensitive. "Basic" is not a
	// supported value. Default: "Bearer"
	Type *string `json:"type,omitempty"`
}

// AuthorizationApplyConfiguration constructs a declarative configuration of the Authorization type for use with
// apply.
func Authorization() *AuthorizationApplyConfiguration {
	return &AuthorizationApplyConfiguration{}
}

// WithCredentials sets the Credentials field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Credentials field is set to the value of the last call.
func (b *AuthorizationApplyConfiguration) WithCredentials(value *CredentialsApplyConfiguration) *AuthorizationApplyConfiguration {
	b.Credentials = value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AuthorizationApplyConfiguration) WithType(value string) *AuthorizationApplyConfiguration {
	b.Type = &value
	return b
}
