// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AuthserviceClientApplyConfiguration represents a declarative configuration of the AuthserviceClient type for use
// with apply.
type AuthserviceClientApplyConfiguration struct {
	ClientID *string           `json:"clientId,omitempty"`
	Selector map[string]string `json:"selector,omitempty"`
}

// AuthserviceClientApplyConfiguration constructs a declarative configuration of the AuthserviceClient type for use with
// apply.
func AuthserviceClient() *AuthserviceClientApplyConfiguration {
	return &AuthserviceClientApplyConfiguration{}
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *AuthserviceClientApplyConfiguration) WithClientID(value string) *AuthserviceClientApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithSelector puts the entries into the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Selector field,
// overwriting an existing map entries in Selector field with the same key.
func (b *AuthserviceClientApplyConfiguration) WithSelector(entries map[string]string) *AuthserviceClientApplyConfiguration {
	if b.Selector == nil && len(entries) > 0 {
		b.Selector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Selector[k] = v
	}
	return b
}
