// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BodyApplyConfiguration represents a declarative configuration of the Body type for use
// with apply.
//
// Specifies the content of the response body.
type BodyApplyConfiguration struct {
	// response body as base64 encoded bytes.
	Bytes  *string `json:"bytes,omitempty"`
	String *string `json:"string,omitempty"`
}

// BodyApplyConfiguration constructs a declarative configuration of the Body type for use with
// apply.
func Body() *BodyApplyConfiguration {
	return &BodyApplyConfiguration{}
}

// WithBytes sets the Bytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bytes field is set to the value of the last call.
func (b *BodyApplyConfiguration) WithBytes(value string) *BodyApplyConfiguration {
	b.Bytes = &value
	return b
}

// WithString sets the String field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the String field is set to the value of the last call.
func (b *BodyApplyConfiguration) WithString(value string) *BodyApplyConfiguration {
	b.String = &value
	return b
}
