// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CABundleApplyConfiguration represents a declarative configuration of the CABundle type for use
// with apply.
//
// CA bundle configuration for the package
type CABundleApplyConfiguration struct {
	// ConfigMap configuration for CA bundle
	ConfigMap *ConfigMapApplyConfiguration `json:"configMap,omitempty"`
}

// CABundleApplyConfiguration constructs a declarative configuration of the CABundle type for use with
// apply.
func CABundle() *CABundleApplyConfiguration {
	return &CABundleApplyConfiguration{}
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *CABundleApplyConfiguration) WithConfigMap(value *ConfigMapApplyConfiguration) *CABundleApplyConfiguration {
	b.ConfigMap = value
	return b
}
