// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ChecksApplyConfiguration represents a declarative configuration of the Checks type for use
// with apply.
//
// HTTP probe checks configuration for blackbox-exporter. Defining paths enables uptime
// monitoring.
type ChecksApplyConfiguration struct {
	// List of paths to check for uptime monitoring, appended to the host.
	Paths []string `json:"paths,omitempty"`
}

// ChecksApplyConfiguration constructs a declarative configuration of the Checks type for use with
// apply.
func Checks() *ChecksApplyConfiguration {
	return &ChecksApplyConfiguration{}
}

// WithPaths adds the given value to the Paths field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Paths field.
func (b *ChecksApplyConfiguration) WithPaths(values ...string) *ChecksApplyConfiguration {
	for i := range values {
		b.Paths = append(b.Paths, values[i])
	}
	return b
}
