// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterConfigExposeApplyConfiguration represents a declarative configuration of the ClusterConfigExpose type for use
// with apply.
//
// ClusterConfigExpose configures the domains cluster services are exposed on.
type ClusterConfigExposeApplyConfiguration struct {
	// Domain is the domain all cluster services are exposed on. Required.
	Domain *string `json:"domain,omitempty"`
	// AdminDomain is the domain for admin gateway services. Defaults to "admin.<domain>".
	AdminDomain *string `json:"adminDomain,omitempty"`
}

// ClusterConfigExposeApplyConfiguration constructs a declarative configuration of the ClusterConfigExpose type for use with
// apply.
func ClusterConfigExpose() *ClusterConfigExposeApplyConfiguration {
	return &ClusterConfigExposeApplyConfiguration{}
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *ClusterConfigExposeApplyConfiguration) WithDomain(value string) *ClusterConfigExposeApplyConfiguration {
	b.Domain = &value
	return b
}

// WithAdminDomain sets the AdminDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminDomain field is set to the value of the last call.
func (b *ClusterConfigExposeApplyConfiguration) WithAdminDomain(value string) *ClusterConfigExposeApplyConfiguration {
	b.AdminDomain = &value
	return b
}
