// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterConfigAttributesApplyConfiguration represents a declarative configuration of the ClusterConfigAttributes type for use
// with apply.
//
// ClusterConfigAttributes provides optional metadata about the cluster.
type ClusterConfigAttributesApplyConfiguration struct {
	// ClusterName is a friendly name to associate with the UDS cluster.
	ClusterName *string `json:"clusterName,omitempty"`
	// Tags are labels to apply to the UDS cluster.
	Tags []string `json:"tags,omitempty"`
}

// ClusterConfigAttributesApplyConfiguration constructs a declarative configuration of the ClusterConfigAttributes type for use with
// apply.
func ClusterConfigAttributes() *ClusterConfigAttributesApplyConfiguration {
	return &ClusterConfigAttributesApplyConfiguration{}
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *ClusterConfigAttributesApplyConfiguration) WithClusterName(value string) *ClusterConfigAttributesApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *ClusterConfigAttributesApplyConfiguration) WithTags(values ...string) *ClusterConfigAttributesApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}
