// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterConfigNetworkingApplyConfiguration represents a declarative configuration of the ClusterConfigNetworking type for use
// with apply.
//
// ClusterConfigNetworking holds optional CIDR overrides used to generate network policies.
type ClusterConfigNetworkingApplyConfiguration struct {
	// KubeApiCIDR is the CIDR range for Kubernetes control plane nodes.
	KubeApiCIDR *string `json:"kubeApiCIDR,omitempty"`
	// KubeNodeCIDRs are the CIDRs for all Kubernetes nodes.
	KubeNodeCIDRs []string `json:"kubeNodeCIDRs,omitempty"`
}

// ClusterConfigNetworkingApplyConfiguration constructs a declarative configuration of the ClusterConfigNetworking type for use with
// apply.
func ClusterConfigNetworking() *ClusterConfigNetworkingApplyConfiguration {
	return &ClusterConfigNetworkingApplyConfiguration{}
}

// WithKubeApiCIDR sets the KubeApiCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeApiCIDR field is set to the value of the last call.
func (b *ClusterConfigNetworkingApplyConfiguration) WithKubeApiCIDR(value string) *ClusterConfigNetworkingApplyConfiguration {
	b.KubeApiCIDR = &value
	return b
}

// WithKubeNodeCIDRs adds the given value to the KubeNodeCIDRs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the KubeNodeCIDRs field.
func (b *ClusterConfigNetworkingApplyConfiguration) WithKubeNodeCIDRs(values ...string) *ClusterConfigNetworkingApplyConfiguration {
	for i := range values {
		b.KubeNodeCIDRs = append(b.KubeNodeCIDRs, values[i])
	}
	return b
}
