// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterConfigCABundleApplyConfiguration represents a declarative configuration of the ClusterConfigCABundle type for use
// with apply.
//
// ClusterConfigCABundle configures the cluster CA certificate bundle.
type ClusterConfigCABundleApplyConfiguration struct {
	// Certs is the base64-encoded PEM bundle of user-provided CA certificates.
	Certs *string `json:"certs,omitempty"`
	// IncludeDoDCerts controls whether DoD CA certificates are included in the bundle.
	IncludeDoDCerts *bool `json:"includeDoDCerts,omitempty"`
	// IncludePublicCerts controls whether public CA certificates are included in the bundle.
	IncludePublicCerts *bool `json:"includePublicCerts,omitempty"`
}

// ClusterConfigCABundleApplyConfiguration constructs a declarative configuration of the ClusterConfigCABundle type for use with
// apply.
func ClusterConfigCABundle() *ClusterConfigCABundleApplyConfiguration {
	return &ClusterConfigCABundleApplyConfiguration{}
}

// WithCerts sets the Certs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Certs field is set to the value of the last call.
func (b *ClusterConfigCABundleApplyConfiguration) WithCerts(value string) *ClusterConfigCABundleApplyConfiguration {
	b.Certs = &value
	return b
}

// WithIncludeDoDCerts sets the IncludeDoDCerts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncludeDoDCerts field is set to the value of the last call.
func (b *ClusterConfigCABundleApplyConfiguration) WithIncludeDoDCerts(value bool) *ClusterConfigCABundleApplyConfiguration {
	b.IncludeDoDCerts = &value
	return b
}

// WithIncludePublicCerts sets the IncludePublicCerts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncludePublicCerts field is set to the value of the last call.
func (b *ClusterConfigCABundleApplyConfiguration) WithIncludePublicCerts(value bool) *ClusterConfigCABundleApplyConfiguration {
	b.IncludePublicCerts = &value
	return b
}
