// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterConfigSpecApplyConfiguration represents a declarative configuration of the ClusterConfigSpec type for use
// with apply.
type ClusterConfigSpecApplyConfiguration struct {
	// Attributes provides optional metadata about the cluster.
	Attributes *ClusterConfigAttributesApplyConfiguration `json:"attributes,omitempty"`
	// Networking holds optional CIDR overrides for kube-apiserver and nodes.
	Networking *ClusterConfigNetworkingApplyConfiguration `json:"networking,omitempty"`
	// CABundle configures the cluster CA certificate bundle.
	CABundle *ClusterConfigCABundleApplyConfiguration `json:"caBundle,omitempty"`
	// Expose configures the domains cluster services are exposed on. Required.
	Expose *ClusterConfigExposeApplyConfiguration `json:"expose,omitempty"`
	// Policy configures cluster-wide policy settings. Required.
	Policy *ClusterConfigPolicyApplyConfiguration `json:"policy,omitempty"`
}

// ClusterConfigSpecApplyConfiguration constructs a declarative configuration of the ClusterConfigSpec type for use with
// apply.
func ClusterConfigSpec() *ClusterConfigSpecApplyConfiguration {
	return &ClusterConfigSpecApplyConfiguration{}
}

// WithAttributes sets the Attributes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attributes field is set to the value of the last call.
func (b *ClusterConfigSpecApplyConfiguration) WithAttributes(value *ClusterConfigAttributesApplyConfiguration) *ClusterConfigSpecApplyConfiguration {
	b.Attributes = value
	return b
}

// WithNetworking sets the Networking field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Networking field is set to the value of the last call.
func (b *ClusterConfigSpecApplyConfiguration) WithNetworking(value *ClusterConfigNetworkingApplyConfiguration) *ClusterConfigSpecApplyConfiguration {
	b.Networking = value
	return b
}

// WithCABundle sets the CABundle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CABundle field is set to the value of the last call.
func (b *ClusterConfigSpecApplyConfiguration) WithCABundle(value *ClusterConfigCABundleApplyConfiguration) *ClusterConfigSpecApplyConfiguration {
	b.CABundle = value
	return b
}

// WithExpose sets the Expose field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expose field is set to the value of the last call.
func (b *ClusterConfigSpecApplyConfiguration) WithExpose(value *ClusterConfigExposeApplyConfiguration) *ClusterConfigSpecApplyConfiguration {
	b.Expose = value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *ClusterConfigSpecApplyConfiguration) WithPolicy(value *ClusterConfigPolicyApplyConfiguration) *ClusterConfigSpecApplyConfiguration {
	b.Policy = value
	return b
}
