// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterConfigPolicyApplyConfiguration represents a declarative configuration of the ClusterConfigPolicy type for use
// with apply.
//
// ClusterConfigPolicy configures cluster-wide policy settings.
type ClusterConfigPolicyApplyConfiguration struct {
	// AllowAllNsExemptions controls whether UDS Exemption CRs may live in any namespace.
	AllowAllNsExemptions *bool `json:"allowAllNsExemptions,omitempty"`
}

// ClusterConfigPolicyApplyConfiguration constructs a declarative configuration of the ClusterConfigPolicy type for use with
// apply.
func ClusterConfigPolicy() *ClusterConfigPolicyApplyConfiguration {
	return &ClusterConfigPolicyApplyConfiguration{}
}

// WithAllowAllNsExemptions sets the AllowAllNsExemptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowAllNsExemptions field is set to the value of the last call.
func (b *ClusterConfigPolicyApplyConfiguration) WithAllowAllNsExemptions(value bool) *ClusterConfigPolicyApplyConfiguration {
	b.AllowAllNsExemptions = &value
	return b
}
