// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConfigMapApplyConfiguration represents a declarative configuration of the ConfigMap type for use
// with apply.
//
// ConfigMap configuration for CA bundle
type ConfigMapApplyConfiguration struct {
	// Additional annotations to apply to the generated ConfigMap (default: {})
	Annotations map[string]string `json:"annotations,omitempty"`
	// The key name inside the ConfigMap (default: ca-bundle.pem)
	Key *string `json:"key,omitempty"`
	// Additional labels to apply to the generated ConfigMap (default: {})
	Labels map[string]string `json:"labels,omitempty"`
	// The name of the ConfigMap to create (default: uds-trust-bundle)
	Name *string `json:"name,omitempty"`
}

// ConfigMapApplyConfiguration constructs a declarative configuration of the ConfigMap type for use with
// apply.
func ConfigMap() *ConfigMapApplyConfiguration {
	return &ConfigMapApplyConfiguration{}
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ConfigMapApplyConfiguration) WithAnnotations(entries map[string]string) *ConfigMapApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ConfigMapApplyConfiguration) WithKey(value string) *ConfigMapApplyConfiguration {
	b.Key = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ConfigMapApplyConfiguration) WithLabels(entries map[string]string) *ConfigMapApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ConfigMapApplyConfiguration) WithName(value string) *ConfigMapApplyConfiguration {
	b.Name = &value
	return b
}
