// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CredentialsApplyConfiguration represents a declarative configuration of the Credentials type for use
// with apply.
//
// Selects a key of a Secret in the namespace that contains the credentials for
// authentication.
type CredentialsApplyConfiguration struct {
	// The key of the secret to select from. Must be a valid secret key.
	Key *string `json:"key,omitempty"`
	// Name of the referent. More info:
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// CredentialsApplyConfiguration constructs a declarative configuration of the Credentials type for use with
// apply.
func Credentials() *CredentialsApplyConfiguration {
	return &CredentialsApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *CredentialsApplyConfiguration) WithKey(value string) *CredentialsApplyConfiguration {
	b.Key = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CredentialsApplyConfiguration) WithName(value string) *CredentialsApplyConfiguration {
	b.Name = &value
	return b
}

// WithOptional sets the Optional field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Optional field is set to the value of the last call.
func (b *CredentialsApplyConfiguration) WithOptional(value bool) *CredentialsApplyConfiguration {
	b.Optional = &value
	return b
}
