// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DirectResponseApplyConfiguration represents a declarative configuration of the DirectResponse type for use
// with apply.
//
// A HTTP rule can either return a direct_response, redirect or forward (default) traffic.
type DirectResponseApplyConfiguration struct {
	// Specifies the content of the response body.
	Body *BodyApplyConfiguration `json:"body,omitempty"`
	// Specifies the HTTP response status to be returned.
	Status *int64 `json:"status,omitempty"`
}

// DirectResponseApplyConfiguration constructs a declarative configuration of the DirectResponse type for use with
// apply.
func DirectResponse() *DirectResponseApplyConfiguration {
	return &DirectResponseApplyConfiguration{}
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *DirectResponseApplyConfiguration) WithBody(value *BodyApplyConfiguration) *DirectResponseApplyConfiguration {
	b.Body = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *DirectResponseApplyConfiguration) WithStatus(value int64) *DirectResponseApplyConfiguration {
	b.Status = &value
	return b
}
