// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ExposeApplyConfiguration represents a declarative configuration of the Expose type for use
// with apply.
type ExposeApplyConfiguration struct {
	// Advanced HTTP settings for the route.
	AdvancedHTTP *AdvancedHTTPApplyConfiguration `json:"advancedHTTP,omitempty"`
	// A description of this expose entry, this will become part of the VirtualService name
	Description *string `json:"description,omitempty"`
	// The domain to expose the service on, only valid for additional gateways (not tenant,
	// admin, or passthrough)
	Domain *string `json:"domain,omitempty"`
	// The name of the gateway to expose the service on (default: tenant)
	Gateway *string `json:"gateway,omitempty"`
	// The hostname to expose the service on
	Host *string `json:"host,omitempty"`
	// Match conditions to be satisfied for the rule to be activated. Not permitted when using
	// the passthrough gateway.
	Match []ExposeMatchApplyConfiguration `json:"match,omitempty"`
	// Deprecated: use selector
	PodLabels map[string]string `json:"podLabels,omitempty"`
	// The port number to expose
	Port *float64 `json:"port,omitempty"`
	// Selector for Pods targeted by the selected Services (so the NetworkPolicy can be
	// generated correctly).
	Selector map[string]string `json:"selector,omitempty"`
	// The name of the service to expose
	Service *string `json:"service,omitempty"`
	// The service targetPort. This defaults to port and is only required if the service port is
	// different from the target port (so the NetworkPolicy can be generated correctly).
	TargetPort *float64 `json:"targetPort,omitempty"`
	// Uptime monitoring configuration for this exposed service. Presence of checks.paths
	// enables monitoring.
	Uptime *UptimeApplyConfiguration `json:"uptime,omitempty"`
}

// ExposeApplyConfiguration constructs a declarative configuration of the Expose type for use with
// apply.
func Expose() *ExposeApplyConfiguration {
	return &ExposeApplyConfiguration{}
}

// WithAdvancedHTTP sets the AdvancedHTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdvancedHTTP field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithAdvancedHTTP(value *AdvancedHTTPApplyConfiguration) *ExposeApplyConfiguration {
	b.AdvancedHTTP = value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithDescription(value string) *ExposeApplyConfiguration {
	b.Description = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithDomain(value string) *ExposeApplyConfiguration {
	b.Domain = &value
	return b
}

// WithGateway sets the Gateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateway field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithGateway(value string) *ExposeApplyConfiguration {
	b.Gateway = &value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithHost(value string) *ExposeApplyConfiguration {
	b.Host = &value
	return b
}

// WithMatch adds the given value to the Match field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Match field.
func (b *ExposeApplyConfiguration) WithMatch(values ...*ExposeMatchApplyConfiguration) *ExposeApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMatch")
		}
		b.Match = append(b.Match, *values[i])
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *ExposeApplyConfiguration) WithPodLabels(entries map[string]string) *ExposeApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithPort(value float64) *ExposeApplyConfiguration {
	b.Port = &value
	return b
}

// WithSelector puts the entries into the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Selector field,
// overwriting an existing map entries in Selector field with the same key.
func (b *ExposeApplyConfiguration) WithSelector(entries map[string]string) *ExposeApplyConfiguration {
	if b.Selector == nil && len(entries) > 0 {
		b.Selector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Selector[k] = v
	}
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithService(value string) *ExposeApplyConfiguration {
	b.Service = &value
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithTargetPort(value float64) *ExposeApplyConfiguration {
	b.TargetPort = &value
	return b
}

// WithUptime sets the Uptime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Uptime field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithUptime(value *UptimeApplyConfiguration) *ExposeApplyConfiguration {
	b.Uptime = value
	return b
}
