// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GroupsApplyConfiguration represents a declarative configuration of the Groups type for use
// with apply.
//
// The client SSO group type
type GroupsApplyConfiguration struct {
	// List of groups allowed to access the client
	AnyOf []string `json:"anyOf,omitempty"`
}

// GroupsApplyConfiguration constructs a declarative configuration of the Groups type for use with
// apply.
func Groups() *GroupsApplyConfiguration {
	return &GroupsApplyConfiguration{}
}

// WithAnyOf adds the given value to the AnyOf field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AnyOf field.
func (b *GroupsApplyConfiguration) WithAnyOf(values ...string) *GroupsApplyConfiguration {
	for i := range values {
		b.AnyOf = append(b.AnyOf, values[i])
	}
	return b
}
