// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeaderOpApplyConfiguration represents a declarative configuration of the HeaderOp type for use
// with apply.
type HeaderOpApplyConfiguration struct {
	Add    map[string]string `json:"add,omitempty"`
	Remove []string          `json:"remove,omitempty"`
	Set    map[string]string `json:"set,omitempty"`
}

// HeaderOpApplyConfiguration constructs a declarative configuration of the HeaderOp type for use with
// apply.
func HeaderOp() *HeaderOpApplyConfiguration {
	return &HeaderOpApplyConfiguration{}
}

// WithAdd puts the entries into the Add field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Add field,
// overwriting an existing map entries in Add field with the same key.
func (b *HeaderOpApplyConfiguration) WithAdd(entries map[string]string) *HeaderOpApplyConfiguration {
	if b.Add == nil && len(entries) > 0 {
		b.Add = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Add[k] = v
	}
	return b
}

// WithRemove adds the given value to the Remove field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Remove field.
func (b *HeaderOpApplyConfiguration) WithRemove(values ...string) *HeaderOpApplyConfiguration {
	for i := range values {
		b.Remove = append(b.Remove, values[i])
	}
	return b
}

// WithSet puts the entries into the Set field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Set field,
// overwriting an existing map entries in Set field with the same key.
func (b *HeaderOpApplyConfiguration) WithSet(entries map[string]string) *HeaderOpApplyConfiguration {
	if b.Set == nil && len(entries) > 0 {
		b.Set = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Set[k] = v
	}
	return b
}
