// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeadersApplyConfiguration represents a declarative configuration of the Headers type for use
// with apply.
type HeadersApplyConfiguration struct {
	Request  *HeaderOpApplyConfiguration `json:"request,omitempty"`
	Response *HeaderOpApplyConfiguration `json:"response,omitempty"`
}

// HeadersApplyConfiguration constructs a declarative configuration of the Headers type for use with
// apply.
func Headers() *HeadersApplyConfiguration {
	return &HeadersApplyConfiguration{}
}

// WithRequest sets the Request field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Request field is set to the value of the last call.
func (b *HeadersApplyConfiguration) WithRequest(value *HeaderOpApplyConfiguration) *HeadersApplyConfiguration {
	b.Request = value
	return b
}

// WithResponse sets the Response field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Response field is set to the value of the last call.
func (b *HeadersApplyConfiguration) WithResponse(value *HeaderOpApplyConfiguration) *HeadersApplyConfiguration {
	b.Response = value
	return b
}
