// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NetworkApplyConfiguration represents a declarative configuration of the Network type for use
// with apply.
//
// Network configuration for the package
type NetworkApplyConfiguration struct {
	// Allow specific traffic (namespace will have a default-deny policy)
	Allow []AllowApplyConfiguration `json:"allow,omitempty"`
	// Expose a service on an Istio Gateway
	Expose []ExposeApplyConfiguration `json:"expose,omitempty"`
	// Service Mesh configuration for the package
	ServiceMesh *ServiceMeshApplyConfiguration `json:"serviceMesh,omitempty"`
}

// NetworkApplyConfiguration constructs a declarative configuration of the Network type for use with
// apply.
func Network() *NetworkApplyConfiguration {
	return &NetworkApplyConfiguration{}
}

// WithAllow adds the given value to the Allow field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Allow field.
func (b *NetworkApplyConfiguration) WithAllow(values ...*AllowApplyConfiguration) *NetworkApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllow")
		}
		b.Allow = append(b.Allow, *values[i])
	}
	return b
}

// WithExpose adds the given value to the Expose field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Expose field.
func (b *NetworkApplyConfiguration) WithExpose(values ...*ExposeApplyConfiguration) *NetworkApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExpose")
		}
		b.Expose = append(b.Expose, *values[i])
	}
	return b
}

// WithServiceMesh sets the ServiceMesh field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceMesh field is set to the value of the last call.
func (b *NetworkApplyConfiguration) WithServiceMesh(value *ServiceMeshApplyConfiguration) *NetworkApplyConfiguration {
	b.ServiceMesh = value
	return b
}
