// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// ProtocolMapperApplyConfiguration represents a declarative configuration of the ProtocolMapper type for use
// with apply.
type ProtocolMapperApplyConfiguration struct {
	// Configuration options for the mapper.
	Config map[string]string `json:"config,omitempty"`
	// Whether user consent is required for this mapper
	ConsentRequired *bool `json:"consentRequired,omitempty"`
	// Name of the mapper
	Name *string `json:"name,omitempty"`
	// Protocol of the mapper
	Protocol *udsv1alpha1.Protocol `json:"protocol,omitempty"`
	// Protocol Mapper type of the mapper
	ProtocolMapper *string `json:"protocolMapper,omitempty"`
}

// ProtocolMapperApplyConfiguration constructs a declarative configuration of the ProtocolMapper type for use with
// apply.
func ProtocolMapper() *ProtocolMapperApplyConfiguration {
	return &ProtocolMapperApplyConfiguration{}
}

// WithConfig puts the entries into the Config field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Config field,
// overwriting an existing map entries in Config field with the same key.
func (b *ProtocolMapperApplyConfiguration) WithConfig(entries map[string]string) *ProtocolMapperApplyConfiguration {
	if b.Config == nil && len(entries) > 0 {
		b.Config = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Config[k] = v
	}
	return b
}

// WithConsentRequired sets the ConsentRequired field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsentRequired field is set to the value of the last call.
func (b *ProtocolMapperApplyConfiguration) WithConsentRequired(value bool) *ProtocolMapperApplyConfiguration {
	b.ConsentRequired = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ProtocolMapperApplyConfiguration) WithName(value string) *ProtocolMapperApplyConfiguration {
	b.Name = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *ProtocolMapperApplyConfiguration) WithProtocol(value udsv1alpha1.Protocol) *ProtocolMapperApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithProtocolMapper sets the ProtocolMapper field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtocolMapper field is set to the value of the last call.
func (b *ProtocolMapperApplyConfiguration) WithProtocolMapper(value string) *ProtocolMapperApplyConfiguration {
	b.ProtocolMapper = &value
	return b
}
