// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// RedirectApplyConfiguration represents a declarative configuration of the Redirect type for use
// with apply.
//
// A HTTP rule can either return a direct_response, redirect or forward (default) traffic.
type RedirectApplyConfiguration struct {
	// On a redirect, overwrite the Authority/Host portion of the URL with this value.
	Authority *string `json:"authority,omitempty"`
	// On a redirect, dynamically set the port: * FROM_PROTOCOL_DEFAULT: automatically set to 80
	// for HTTP and 443 for HTTPS.
	//
	// Valid Options: FROM_PROTOCOL_DEFAULT, FROM_REQUEST_PORT
	DerivePort *udsv1alpha1.DerivePort `json:"derivePort,omitempty"`
	// On a redirect, overwrite the port portion of the URL with this value.
	Port *int64 `json:"port,omitempty"`
	// On a redirect, Specifies the HTTP status code to use in the redirect response.
	RedirectCode *int64 `json:"redirectCode,omitempty"`
	// On a redirect, overwrite the scheme portion of the URL with this value.
	Scheme *string `json:"scheme,omitempty"`
	// On a redirect, overwrite the Path portion of the URL with this value.
	URI *string `json:"uri,omitempty"`
}

// RedirectApplyConfiguration constructs a declarative configuration of the Redirect type for use with
// apply.
func Redirect() *RedirectApplyConfiguration {
	return &RedirectApplyConfiguration{}
}

// WithAuthority sets the Authority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authority field is set to the value of the last call.
func (b *RedirectApplyConfiguration) WithAuthority(value string) *RedirectApplyConfiguration {
	b.Authority = &value
	return b
}

// WithDerivePort sets the DerivePort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DerivePort field is set to the value of the last call.
func (b *RedirectApplyConfiguration) WithDerivePort(value udsv1alpha1.DerivePort) *RedirectApplyConfiguration {
	b.DerivePort = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *RedirectApplyConfiguration) WithPort(value int64) *RedirectApplyConfiguration {
	b.Port = &value
	return b
}

// WithRedirectCode sets the RedirectCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedirectCode field is set to the value of the last call.
func (b *RedirectApplyConfiguration) WithRedirectCode(value int64) *RedirectApplyConfiguration {
	b.RedirectCode = &value
	return b
}

// WithScheme sets the Scheme field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scheme field is set to the value of the last call.
func (b *RedirectApplyConfiguration) WithScheme(value string) *RedirectApplyConfiguration {
	b.Scheme = &value
	return b
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *RedirectApplyConfiguration) WithURI(value string) *RedirectApplyConfiguration {
	b.URI = &value
	return b
}
