// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SecretConfigApplyConfiguration represents a declarative configuration of the SecretConfig type for use
// with apply.
//
// Configuration for the generated Kubernetes Secret
type SecretConfigApplyConfiguration struct {
	// Additional annotations to apply to the generated secret
	Annotations map[string]string `json:"annotations,omitempty"`
	// Additional labels to apply to the generated secret
	Labels map[string]string `json:"labels,omitempty"`
	// The name of the secret to store the client secret
	Name *string `json:"name,omitempty"`
	// A template for the generated secret
	Template map[string]string `json:"template,omitempty"`
}

// SecretConfigApplyConfiguration constructs a declarative configuration of the SecretConfig type for use with
// apply.
func SecretConfig() *SecretConfigApplyConfiguration {
	return &SecretConfigApplyConfiguration{}
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *SecretConfigApplyConfiguration) WithAnnotations(entries map[string]string) *SecretConfigApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *SecretConfigApplyConfiguration) WithLabels(entries map[string]string) *SecretConfigApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SecretConfigApplyConfiguration) WithName(value string) *SecretConfigApplyConfiguration {
	b.Name = &value
	return b
}

// WithTemplate puts the entries into the Template field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Template field,
// overwriting an existing map entries in Template field with the same key.
func (b *SecretConfigApplyConfiguration) WithTemplate(entries map[string]string) *SecretConfigApplyConfiguration {
	if b.Template == nil && len(entries) > 0 {
		b.Template = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Template[k] = v
	}
	return b
}
