// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// ServiceMeshApplyConfiguration represents a declarative configuration of the ServiceMesh type for use
// with apply.
//
// Service Mesh configuration for the package
type ServiceMeshApplyConfiguration struct {
	// Set the service mesh mode for this package (namespace), defaults to ambient
	Mode *udsv1alpha1.Mode `json:"mode,omitempty"`
}

// ServiceMeshApplyConfiguration constructs a declarative configuration of the ServiceMesh type for use with
// apply.
func ServiceMesh() *ServiceMeshApplyConfiguration {
	return &ServiceMeshApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *ServiceMeshApplyConfiguration) WithMode(value udsv1alpha1.Mode) *ServiceMeshApplyConfiguration {
	b.Mode = &value
	return b
}
