// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SpecApplyConfiguration represents a declarative configuration of the Spec type for use
// with apply.
type SpecApplyConfiguration struct {
	// CA bundle configuration for the package
	CABundle *CABundleApplyConfiguration `json:"caBundle,omitempty"`
	// Create Service or Pod Monitor configurations
	Monitor []MonitorApplyConfiguration `json:"monitor,omitempty"`
	// Network configuration for the package
	Network *NetworkApplyConfiguration `json:"network,omitempty"`
	// Create SSO client configurations
	Sso []SsoApplyConfiguration `json:"sso,omitempty"`
}

// SpecApplyConfiguration constructs a declarative configuration of the Spec type for use with
// apply.
func Spec() *SpecApplyConfiguration {
	return &SpecApplyConfiguration{}
}

// WithCABundle sets the CABundle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CABundle field is set to the value of the last call.
func (b *SpecApplyConfiguration) WithCABundle(value *CABundleApplyConfiguration) *SpecApplyConfiguration {
	b.CABundle = value
	return b
}

// WithMonitor adds the given value to the Monitor field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Monitor field.
func (b *SpecApplyConfiguration) WithMonitor(values ...*MonitorApplyConfiguration) *SpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMonitor")
		}
		b.Monitor = append(b.Monitor, *values[i])
	}
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *SpecApplyConfiguration) WithNetwork(value *NetworkApplyConfiguration) *SpecApplyConfiguration {
	b.Network = value
	return b
}

// WithSso adds the given value to the Sso field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sso field.
func (b *SpecApplyConfiguration) WithSso(values ...*SsoApplyConfiguration) *SpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSso")
		}
		b.Sso = append(b.Sso, *values[i])
	}
	return b
}
