// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// StatusClassApplyConfiguration represents a declarative configuration of the StatusClass type for use
// with apply.
//
// PackageStatus is an alias for the generated StatusClass type.
type StatusClassApplyConfiguration struct {
	AuthorizationPolicyCount *int64                                `json:"authorizationPolicyCount,omitempty"`
	AuthserviceClients       []AuthserviceClientApplyConfiguration `json:"authserviceClients,omitempty"`
	// Status conditions following Kubernetes-style conventions
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
	Endpoints  []string                      `json:"endpoints,omitempty"`
	// The current service mesh mode for this package
	MeshMode           *udsv1alpha1.Mode  `json:"meshMode,omitempty"`
	Monitors           []string           `json:"monitors,omitempty"`
	NetworkPolicyCount *int64             `json:"networkPolicyCount,omitempty"`
	ObservedGeneration *int64             `json:"observedGeneration,omitempty"`
	Phase              *udsv1alpha1.Phase `json:"phase,omitempty"`
	Probes             []string           `json:"probes,omitempty"`
	RetryAttempt       *int64             `json:"retryAttempt,omitempty"`
	SsoClients         []string           `json:"ssoClients,omitempty"`
}

// StatusClassApplyConfiguration constructs a declarative configuration of the StatusClass type for use with
// apply.
func StatusClass() *StatusClassApplyConfiguration {
	return &StatusClassApplyConfiguration{}
}

// WithAuthorizationPolicyCount sets the AuthorizationPolicyCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorizationPolicyCount field is set to the value of the last call.
func (b *StatusClassApplyConfiguration) WithAuthorizationPolicyCount(value int64) *StatusClassApplyConfiguration {
	b.AuthorizationPolicyCount = &value
	return b
}

// WithAuthserviceClients adds the given value to the AuthserviceClients field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuthserviceClients field.
func (b *StatusClassApplyConfiguration) WithAuthserviceClients(values ...*AuthserviceClientApplyConfiguration) *StatusClassApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAuthserviceClients")
		}
		b.AuthserviceClients = append(b.AuthserviceClients, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *StatusClassApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *StatusClassApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *StatusClassApplyConfiguration) WithEndpoints(values ...string) *StatusClassApplyConfiguration {
	for i := range values {
		b.Endpoints = append(b.Endpoints, values[i])
	}
	return b
}

// WithMeshMode sets the MeshMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MeshMode field is set to the value of the last call.
func (b *StatusClassApplyConfiguration) WithMeshMode(value udsv1alpha1.Mode) *StatusClassApplyConfiguration {
	b.MeshMode = &value
	return b
}

// WithMonitors adds the given value to the Monitors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Monitors field.
func (b *StatusClassApplyConfiguration) WithMonitors(values ...string) *StatusClassApplyConfiguration {
	for i := range values {
		b.Monitors = append(b.Monitors, values[i])
	}
	return b
}

// WithNetworkPolicyCount sets the NetworkPolicyCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkPolicyCount field is set to the value of the last call.
func (b *StatusClassApplyConfiguration) WithNetworkPolicyCount(value int64) *StatusClassApplyConfiguration {
	b.NetworkPolicyCount = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *StatusClassApplyConfiguration) WithObservedGeneration(value int64) *StatusClassApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *StatusClassApplyConfiguration) WithPhase(value udsv1alpha1.Phase) *StatusClassApplyConfiguration {
	b.Phase = &value
	return b
}

// WithProbes adds the given value to the Probes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Probes field.
func (b *StatusClassApplyConfiguration) WithProbes(values ...string) *StatusClassApplyConfiguration {
	for i := range values {
		b.Probes = append(b.Probes, values[i])
	}
	return b
}

// WithRetryAttempt sets the RetryAttempt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryAttempt field is set to the value of the last call.
func (b *StatusClassApplyConfiguration) WithRetryAttempt(value int64) *StatusClassApplyConfiguration {
	b.RetryAttempt = &value
	return b
}

// WithSsoClients adds the given value to the SsoClients field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SsoClients field.
func (b *StatusClassApplyConfiguration) WithSsoClients(values ...string) *StatusClassApplyConfiguration {
	for i := range values {
		b.SsoClients = append(b.SsoClients, values[i])
	}
	return b
}
