// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// StringMatchApplyConfiguration represents a declarative configuration of the StringMatch type for use
// with apply.
//
// StringMatch is a reusable string match type (exact, prefix, or regex).
type StringMatchApplyConfiguration struct {
	Exact  *string `json:"exact,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
	// [RE2 style regex-based match](https://github.com/google/re2/wiki/Syntax).
	Regex *string `json:"regex,omitempty"`
}

// StringMatchApplyConfiguration constructs a declarative configuration of the StringMatch type for use with
// apply.
func StringMatch() *StringMatchApplyConfiguration {
	return &StringMatchApplyConfiguration{}
}

// WithExact sets the Exact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exact field is set to the value of the last call.
func (b *StringMatchApplyConfiguration) WithExact(value string) *StringMatchApplyConfiguration {
	b.Exact = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *StringMatchApplyConfiguration) WithPrefix(value string) *StringMatchApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithRegex sets the Regex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Regex field is set to the value of the last call.
func (b *StringMatchApplyConfiguration) WithRegex(value string) *StringMatchApplyConfiguration {
	b.Regex = &value
	return b
}
