// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// UptimeApplyConfiguration represents a declarative configuration of the Uptime type for use
// with apply.
//
// Uptime monitoring configuration for this exposed service. Presence of checks.paths
// enables monitoring.
type UptimeApplyConfiguration struct {
	// HTTP probe checks configuration for blackbox-exporter. Defining paths enables uptime
	// monitoring.
	Checks *ChecksApplyConfiguration `json:"checks,omitempty"`
}

// UptimeApplyConfiguration constructs a declarative configuration of the Uptime type for use with
// apply.
func Uptime() *UptimeApplyConfiguration {
	return &UptimeApplyConfiguration{}
}

// WithChecks sets the Checks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Checks field is set to the value of the last call.
func (b *UptimeApplyConfiguration) WithChecks(value *ChecksApplyConfiguration) *UptimeApplyConfiguration {
	b.Checks = value
	return b
}
