// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// URIRegexRewriteApplyConfiguration represents a declarative configuration of the URIRegexRewrite type for use
// with apply.
//
// rewrite the path portion of the URI with the specified regex.
type URIRegexRewriteApplyConfiguration struct {
	// [RE2 style regex-based match](https://github.com/google/re2/wiki/Syntax).
	Match *string `json:"match,omitempty"`
	// The string that should replace into matching portions of original URI.
	Rewrite *string `json:"rewrite,omitempty"`
}

// URIRegexRewriteApplyConfiguration constructs a declarative configuration of the URIRegexRewrite type for use with
// apply.
func URIRegexRewrite() *URIRegexRewriteApplyConfiguration {
	return &URIRegexRewriteApplyConfiguration{}
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *URIRegexRewriteApplyConfiguration) WithMatch(value string) *URIRegexRewriteApplyConfiguration {
	b.Match = &value
	return b
}

// WithRewrite sets the Rewrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rewrite field is set to the value of the last call.
func (b *URIRegexRewriteApplyConfiguration) WithRewrite(value string) *URIRegexRewriteApplyConfiguration {
	b.Rewrite = &value
	return b
}
