// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiudsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	versioned "github.com/defenseunicorns/uds-core/src/go-controller/client/clientset/versioned"
	internalinterfaces "github.com/defenseunicorns/uds-core/src/go-controller/client/informers/externalversions/internalinterfaces"
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/listers/uds/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterConfigInformer provides access to a shared informer and lister for
// ClusterConfig.
type ClusterConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() udsv1alpha1.ClusterConfigLister
}

type clusterConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterConfigInformer constructs a new informer for ClusterConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterConfigInformer constructs a new informer for ClusterConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().ClusterConfig(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().ClusterConfig(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().ClusterConfig(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().ClusterConfig(namespace).Watch(ctx, options)
			},
		}, client),
		&apiudsv1alpha1.ClusterConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiudsv1alpha1.ClusterConfig{}, f.defaultInformer)
}

func (f *clusterConfigInformer) Lister() udsv1alpha1.ClusterConfigLister {
	return udsv1alpha1.NewClusterConfigLister(f.Informer().GetIndexer())
}
