// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/defenseunicorns/uds-core/src/go-controller/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// UDSPackages returns a UDSPackageInformer.
	UDSPackages() UDSPackageInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// UDSPackages returns a UDSPackageInformer.
func (v *version) UDSPackages() UDSPackageInformer {
	return &uDSPackageInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
