// Copyright 2025 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiudsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	versioned "github.com/defenseunicorns/uds-core/src/go-controller/client/clientset/versioned"
	internalinterfaces "github.com/defenseunicorns/uds-core/src/go-controller/client/informers/externalversions/internalinterfaces"
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/client/listers/uds/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// UDSPackageInformer provides access to a shared informer and lister for
// UDSPackages.
type UDSPackageInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() udsv1alpha1.UDSPackageLister
}

type uDSPackageInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewUDSPackageInformer constructs a new informer for UDSPackage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewUDSPackageInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredUDSPackageInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredUDSPackageInformer constructs a new informer for UDSPackage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredUDSPackageInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UdsV1alpha1().UDSPackages(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UdsV1alpha1().UDSPackages(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UdsV1alpha1().UDSPackages(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UdsV1alpha1().UDSPackages(namespace).Watch(ctx, options)
			},
		}, client),
		&apiudsv1alpha1.UDSPackage{},
		resyncPeriod,
		indexers,
	)
}

func (f *uDSPackageInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredUDSPackageInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *uDSPackageInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiudsv1alpha1.UDSPackage{}, f.defaultInformer)
}

func (f *uDSPackageInformer) Lister() udsv1alpha1.UDSPackageLister {
	return udsv1alpha1.NewUDSPackageLister(f.Informer().GetIndexer())
}
