# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables = {
  PEPR_WATCHER_MEMORY_REQUEST   = "64Mi"
  PEPR_ADMISSION_MEMORY_REQUEST = "64Mi"
  PEPR_WATCHER_CPU_REQUEST      = "100m"
  PEPR_ADMISSION_CPU_REQUEST    = "100m"

  ISTIOD_MEMORY_REQUEST = "1024Mi"
  ISTIOD_CPU_REQUEST    = "100m"
  PROXY_MEMORY_REQUEST  = "40Mi"
  PROXY_MEMORY_LIMIT    = "1024Mi"
  PROXY_CPU_REQUEST     = "10m"
  PROXY_CPU_LIMIT       = "2000m"

  AUTHSERVICE_REPLICA_COUNT = "1"

  KEYCLOAK_MEMORY_REQUEST          = "700Mi"
  KEYCLOAK_CPU_REQUEST             = "100m"
  KEYCLOAK_MEMORY_LIMIT            = "2Gi"
  KEYCLOAK_CPU_LIMIT               = "2"
  KEYCLOAK_WAYPOINT_HPA_ENABLED    = "false"
  KEYCLOAK_WAYPOINT_CPU_REQUEST    = "100m"
  KEYCLOAK_WAYPOINT_MEMORY_REQUEST = "64Mi"
}
