{
 "title": "UDS / Keycloak / Notifications",
 "description": "This dashboard is used to preview Keycloak Notifications metrics that are used for alerting",
 "tags": [
  "keycloak",
  "uds"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Realm modifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Realm modifications",
   "type": "timeseries",
   "description": "uds_keycloak:uds_realm_modifications_count",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "uds_keycloak:realm_modifications_count",
     "legendFormat": "{{realmName}}"
    }
   ]
  },
  {
   "title": "Realm Modification Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"keycloak\", namespace=\"keycloak\"} | json | loggerName=\"uds.keycloak.plugin.eventListeners.JSONLogEventListenerProvider\" | eventType=\"ADMIN\""
    },
    {
     "direction": "backward",
     "expr": "{app=\"keycloak\", namespace=\"keycloak\"} !~ \"type=\" | json | loggerName=~`org.keycloak.events` | line_format \"{{.message}}\""
    }
   ]
  },
  {
   "title": "User Modifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Admin User Modifications",
   "type": "timeseries",
   "description": "uds_keycloak:uds_system_admin_modifications_count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "uds_keycloak:system_admin_modifications_count",
     "legendFormat": "{{realmName}}"
    }
   ]
  },
  {
   "title": "User modifications",
   "type": "timeseries",
   "description": "uds_keycloak:uds_user_modifications_count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "uds_keycloak:user_modifications_count",
     "legendFormat": "{{realmName}}"
    }
   ]
  },
  {
   "title": "User Modification Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"keycloak\", namespace=\"keycloak\"} | json | loggerName=\"uds.keycloak.plugin.eventListeners.JSONLogEventListenerProvider\" | eventType=\"ADMIN\" | resourceType=~\"USER|GROUP_MEMBERSHIP\""
    },
    {
     "direction": "backward",
     "expr": "{app=\"keycloak\", namespace=\"keycloak\"} !~ \"type=\" | json | loggerName=~`org.keycloak.events` | line_format \"{{.message}}\" | logfmt | resourceType=~\"USER|GROUP_MEMBERSHIP\""
    }
   ]
  }
 ]
}