# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: velero
component:
  target:
    flavor: upstream
  import:
    paths:
      - ../common/velero.yaml
  charts:
    - name: velero
      valuesFiles:
        - ../values/upstream-values.yaml
  images:
    - name: velero/velero:v1.18.0
    - name: velero/velero-plugin-for-aws:v1.14.0
    - name: velero/velero-plugin-for-microsoft-azure:v1.14.0
