{
 "title": "Istio Sidecar vs Ambient Resource Comparison",
 "description": "A summary of CPU and Memory usage by namespace. Provides estimated resource savings when switching from Sidecar to Ambient mode.",
 "tags": [
  "istio",
  "uds"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace!~\"kube-system|istio-system|istio-admin-gateway|istio-tenant-gateway|istio-passthrough-gateway|pepr-system|falco|loki|monitoring|grafana|vector|velero|keycloak|authservice|zarf|uds-dev-stack\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Istio Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(count(kube_namespace_labels{label_istio_injection=\"enabled\", namespace=\"$namespace\"}) or vector(0), 1) * 1",
     "legendFormat": "isSidecar"
    },
    {
     "expr": "clamp_max(count(kube_namespace_labels{label_istio_io_dataplane_mode=\"ambient\", namespace=\"$namespace\"}) or vector(0), 1) * 2",
     "legendFormat": "isAmbient"
    }
   ]
  },
  {
   "title": "CPU Usage - All Workloads (With vs Without Istio Sidecar)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", pod!~\".*waypoint.*\"}[1m]))",
     "legendFormat": "With Sidecar"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", container!=\"istio-proxy\"}[1m]))",
     "legendFormat": "Without Sidecar"
    }
   ]
  },
  {
   "title": "Memory Usage - All Workloads (With vs Without Istio Sidecar)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container!=\"\", pod!~\".*waypoint.*\"})",
     "legendFormat": "With Sidecar"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container!=\"\", container!=\"istio-proxy\"})",
     "legendFormat": "Without Sidecar"
    }
   ]
  }
 ]
}