# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfPackageConfig
metadata:
  name: authservice
components:
  - name: authservice
    import:
      local:
        - path: ./flavors/authservice-upstream.yaml
        - path: ./flavors/authservice-registry1.yaml
        - path: ./flavors/authservice-unicorn.yaml
