# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: ghcr.io/defenseunicorns/uds-portal
  # renovate: datasource=docker depName=ghcr.io/defenseunicorns/uds-portal versioning=semver
  tag: "0.4.0"
