# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

package:
  enabled: false
  domain: "###ZARF_VAR_DOMAIN###"
  adminDomain: "###ZARF_VAR_ADMIN_DOMAIN###"

extraVolumeMounts:
  - name: ca-certs
    mountPath: /etc/ssl/certs/ca-bundle.pem
    subPath: ca-bundle.pem
    readOnly: true

extraVolumes:
  - name: ca-certs
    configMap:
      name: uds-trust-bundle
      optional: true
