# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: metrics-server
component:
  target:
    flavor: upstream
  import:
    paths:
      - common/metrics-server.yaml
  charts:
    - name: metrics-server
      valuesFiles:
        - values/upstream-values.yaml
  images:
    - name: registry.k8s.io/metrics-server/metrics-server:v0.8.1
