# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: metrics-server
component:
  target:
    flavor: unicorn
  import:
    paths:
      - common/metrics-server.yaml
  charts:
    - name: metrics-server
      valuesFiles:
        - values/unicorn-values.yaml
  images:
    - name: quay.io/rfcurated/metrics-server:0.8.1-jammy-scratch-fips-rfcurated-rfhardened
