# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfPackageConfig
metadata:
  name: metrics-server
components:
  - name: metrics-server
    import:
      paths:
        - flavors/metrics-server-upstream.yaml
        - flavors/metrics-server-registry1.yaml
        - flavors/metrics-server-unicorn.yaml
