# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: loki
  description: "Install Loki using Rapidfort images"
component:
  target:
    flavor: unicorn
  import:
    paths:
      - common/loki.yaml
  charts:
    - name: loki
      valuesFiles:
        - values/unicorn-values.yaml
  images:
    - name: quay.io/rfcurated/grafana/loki:3.7.1-jammy-fips-rfcurated-rfhardened
    - name: quay.io/rfcurated/nginx:1.29.7-slim-jammy-fips-rfcurated-rfhardened
    - name: quay.io/rfcurated/memcached:1.6.41-jammy-fips-rfcurated-rfhardened
    - name: quay.io/rfcurated/kiwigrid/k8s-sidecar:2.5.0-jammy-scratch-fips-rfcurated-rfhardened
