/**
 * Copyright 2026 Defense Unicorns
 * SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
 *
 * Generate Istio VirtualService schema subset for pepr (advancedHTTP fields)
 * Usage: ISTIO_VERSION=1.28.3 npx ts-node src/pepr/scripts/gen-istio-crd-sources.ts
 * Or via the task: uds run -f src/istio/tasks.yaml gen-crds
 */

import { V1JSONSchemaProps } from "@kubernetes/client-node";
import fs from "fs";
import https from "https";
import yaml from "js-yaml";
import path from "path";

const ISTIO_VERSION = process.env.ISTIO_VERSION;
if (!ISTIO_VERSION) throw new Error("ISTIO_VERSION env var is required (e.g., 1.28.3)");

const CRD_URL = `https://raw.githubusercontent.com/istio/istio/refs/tags/${ISTIO_VERSION}/manifests/charts/base/files/crd-all.gen.yaml`;
// The subset of the HTTP spec that we embed inside our Package CRD
const INCLUDED_HTTP_FIELDS = [
  "corsPolicy",
  "directResponse",
  "headers",
  "match",
  "rewrite",
  "redirect",
  "retries",
  "timeout",
];

function fetchText(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https
      .get(url, res => {
        if (res.statusCode !== 200)
          return reject(new Error(`HTTP ${res.statusCode} fetching ${url}`));
        const chunks: Buffer[] = [];
        res.on("data", d => chunks.push(d));
        res.on("end", () => resolve(Buffer.concat(chunks).toString("utf-8")));
      })
      .on("error", reject);
  });
}

function sanitizeKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sanitizeKeys);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([k, v]) => {
        const newKey = k.startsWith("x-kubernetes") ? k.replace(/-/g, "_") : k;
        return [newKey, sanitizeKeys(v)];
      }),
    );
  }
  return value;
}

async function main() {
  const raw = await fetchText(CRD_URL);
  type CrdVersion = { name?: string; schema?: { openAPIV3Schema?: V1JSONSchemaProps } };
  type CrdDoc = {
    kind?: string;
    metadata?: { name?: string };
    spec?: { versions?: CrdVersion[] };
  };

  const docs = yaml.loadAll(raw) as CrdDoc[];

  const vs = docs.find(
    d =>
      d &&
      typeof d === "object" &&
      d.kind === "CustomResourceDefinition" &&
      d.metadata?.name === "virtualservices.networking.istio.io",
  );
  if (!vs) throw new Error("VirtualService CRD not found in Istio bundle");

  // Grab the VirtualService v1beta1 OpenAPI schema
  const vsVersion = vs.spec?.versions?.find(v => v?.name === "v1beta1");
  const vsSchema = vsVersion?.schema?.openAPIV3Schema;
  if (!vsSchema) throw new Error("VirtualService v1beta1 schema missing");

  // We only need the HTTP route properties for advancedHTTP
  const httpProps = vsSchema.properties?.spec?.properties?.http?.items?.properties as
    | Record<string, V1JSONSchemaProps>
    | undefined;
  if (!httpProps) throw new Error("VirtualService http.items.properties not found");

  // Filter to just the properties we embed in our CRD
  const properties = Object.fromEntries(
    Object.entries(httpProps).filter(([key]) => INCLUDED_HTTP_FIELDS.includes(key)),
  );

  const missing = INCLUDED_HTTP_FIELDS.filter(key => !(key in httpProps));
  if (missing.length)
    console.warn(`Missing expected HTTP fields from upstream schema: ${missing.join(", ")}`);

  const advancedHTTP: V1JSONSchemaProps = {
    description: "Advanced HTTP settings for the route.",
    properties: sanitizeKeys(properties) as Record<string, V1JSONSchemaProps>,
    type: "object",
  };

  const outPath = path.resolve(
    __dirname,
    "../operator/crd/sources/istio/virtualservice-v1beta1.ts",
  );
  const header = [
    "/**",
    ` * Auto-generated from Istio ${ISTIO_VERSION} CRD (virtualservices.networking.istio.io v1beta1).`,
    " * Generated by src/pepr/scripts/gen-istio-crd-sources.ts",
    " * Usage: uds run -f src/istio/tasks.yaml gen-crds",
    " * Do not edit manually.",
    " */",
    'import { V1JSONSchemaProps } from "@kubernetes/client-node";',
    "",
    "export const advancedHTTP: V1JSONSchemaProps = ",
  ].join("\n");

  const jsonStr = JSON.stringify(advancedHTTP, null, 2);
  const tsLiteral = jsonStr.replace(/^(\s*)"([^"\\]+)":/gm, "$1$2:");

  fs.writeFileSync(outPath, `${header}${tsLiteral} as V1JSONSchemaProps;\n`);
  console.log(`Wrote ${outPath}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
