# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: uds-controller-clusterconfig
  labels:
    app: uds-controller
webhooks:
  - name: clusterconfig.uds.dev
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Exact
    clientConfig:
      service:
        name: uds-controller
        namespace: uds-system
        path: /validate-clusterconfig-delete
        port: 443
      caBundle: ""
    rules:
      - apiGroups:
          - uds.dev
        apiVersions:
          - "*"
        resources:
          - clusterconfig
        operations:
          - DELETE
        scope: "Cluster"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: uds-controller-pods
  labels:
    app: uds-controller
webhooks:
  - name: validate-pods.uds.dev
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: uds-controller
        namespace: uds-system
        path: /validate-pods
        port: 443
      caBundle: ""
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
        operations:
          - CREATE
          - UPDATE
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - uds-system
            - pepr-system
            - istio-system
            - zarf
  - name: validate-pods-istio-system.uds.dev
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Ignore
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: uds-controller
        namespace: uds-system
        path: /validate-pods
        port: 443
      caBundle: ""
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
        operations:
          - CREATE
          - UPDATE
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - istio-system
