# Copyright 2024-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: cgr.dev
  repository: defenseunicorns.com/grafana-fips
  tag: 12.4.2

initChownData:
  image:
    registry: cgr.dev
    repository: defenseunicorns.com/busybox-fips
    tag: 1.37.0

downloadDashboardsImage:
  registry: cgr.dev
  repository: defenseunicorns.com/curl-fips
  tag: 8.19.0

sidecar:
  image:
    registry: cgr.dev
    repository: defenseunicorns.com/k8s-sidecar-fips
    tag: 2.5.1
