# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables:
  core:
    # Enable Falco sandbox and incubating rules
    FALCO_SANDBOX_RULES_ENABLED: true
    FALCO_INCUBATING_RULES_ENABLED: true
